In [1]:
import pandas as pd
import numpy as np

In [2]:
cutoff = pd.read_csv('../dataset/sue_cutoffs.csv')
sue = pd.read_csv('../dataset/sue.csv')

In [3]:
cutoff

,Unnamed: 0,10,15,20,25,30,40,50,60,70,75,80,85,90
0,2020-03-31,-3.564696,-2.785541,-2.238445,-1.726030,-1.333524,-0.772274,-0.163857,0.381893,0.938098,1.198657,1.510083,1.965605,2.454226
1,2019-12-31,-2.110828,-1.410253,-1.093586,-0.773738,-0.448948,0.079900,0.589183,1.103181,1.545486,1.815404,2.139856,2.379102,2.662984
2,2019-09-30,-1.617063,-1.244536,-0.936345,-0.640495,-0.367696,0.122470,0.619369,1.109803,1.532296,1.810733,2.102072,2.432977,2.838799
3,2019-06-30,-1.497825,-1.118737,-0.803735,-0.495148,-0.222220,0.217962,0.574483,0.957188,1.386805,1.584325,1.877683,2.262846,2.636423
4,2019-03-31,-1.501021,-1.106272,-0.840493,-0.528025,-0.287363,0.165315,0.611116,0.970800,1.478091,1.617331,1.904388,2.237324,2.623735
5,2018-12-31,-2.050808,-1.443180,-1.028776,-0.602669,-0.297389,0.140110,0.619631,1.039546,1.557811,1.867915,2.193455,2.559379,2.903800
6,2018-09-30,-1.594277,-1.105270,-0.745957,-0.474842,-0.177645,0.287548,0.743215,1.130156,1.698606,1.983352,2.243502,2.588383,2.995161
7,2018-06-30,-1.679224,-1.179673,-0.906012,-0.631060,-0.391262,0.109996,0.518864,0.990822,1.553444,1.838918,2.153243,2.529494,2.958059
8,2018-03-31,-1.759830,-1.243104,-0.944786,-0.756410,-0.527867,0.000000,0.471195,0.922209,1.437025,1.707010,2.026201,2.319677,2.764893
9,2017-12-31,-3.904487,-2.682366,-2.044852,-1.487376,-1.120855,-0.407739,0.227644,0.887191,1.506655,1.812647,2.132881,2.600397,3.175767
10,2017-09-30,-1.658591,-1.186898,-0.884337,-0.563521,-0.304046,0.184537,0.655250,1.149850,1.627521,1.925449,2.246264,2.569348,3.047357
11,2017-06-30,-1.813151,-1.393708,-1.090653,-0.764331,-0.459208,0.068600,0.567625,0.991108,1.419287,1.657762,1.936800,2.310688,2.847553

# Import Data

### Prices data

In [4]:
#read in prices data
df = pd.read_csv('../dataset/price_volume_sorted.csv')
df

        ticker        date   open   high    low  close     volume
0         AAME  2015-01-02  3.990  4.030  3.980  4.030    11443.0
1         AAME  2015-01-05  3.900  4.010  3.900  4.010    13727.0
2         AAME  2015-01-06  3.950  3.950  3.750  3.920     9743.0
3         AAME  2015-01-07  3.899  3.920  3.870  3.920     1486.0
4         AAME  2015-01-08  3.920  3.950  3.915  3.950     2200.0
...        ...         ...    ...    ...    ...    ...        ...
1266080   ZSAN  2020-12-14  0.661  0.673  0.630  0.648  3078592.0
1266081   ZSAN  2020-12-15  0.655  0.662  0.630  0.638  1594117.0
1266082   ZSAN  2020-12-16  0.633  0.645  0.598  0.607  1990734.0
1266083   ZSAN  2020-12-17  0.620  0.620  0.550  0.577  3141599.0
1266084   ZSAN  2020-12-18  0.575  0.610  0.575  0.583  2023953.0

[1266085 rows x 7 columns]

In [5]:
names = ['TCON','TMBR', 'TAT', 'BSTC','ZSAN','RCKT','TAT','LLEXQ','WSTL','NTRP','JCAP','RKDA','RMNI','PATI','ZEUS']
df = df[~df['ticker'].isin(names)]
df

        ticker        date   open   high    low  close     volume
0         AAME  2015-01-02  3.990  4.030  3.980  4.030    11443.0
1         AAME  2015-01-05  3.900  4.010  3.900  4.010    13727.0
2         AAME  2015-01-06  3.950  3.950  3.750  3.920     9743.0
3         AAME  2015-01-07  3.899  3.920  3.870  3.920     1486.0
4         AAME  2015-01-08  3.920  3.950  3.915  3.950     2200.0
...        ...         ...    ...    ...    ...    ...        ...
1264593   ZNOG  2020-12-14  1.020  1.080  1.000  1.000   992087.0
1264594   ZNOG  2020-12-15  1.010  1.020  0.801  0.810  3780405.0
1264595   ZNOG  2020-12-16  0.800  0.930  0.600  0.910  4584326.0
1264596   ZNOG  2020-12-17  0.945  0.945  0.860  0.902   835431.0
1264597   ZNOG  2020-12-18  0.910  0.910  0.810  0.860   770447.0

[1245593 rows x 7 columns]

In [6]:
price_volume_sorted_list = df['ticker'].unique().tolist()
#i need date, closing price, ticker
#also rename the column
prices = df.drop(columns = {'open','high','low','volume'})
prices.rename(columns={'ticker':'Ticker'}, inplace =True)

In [7]:
len(prices.Ticker.unique())

829

In [8]:
#change date column into datetime
prices['date']= pd.to_datetime(prices['date'],dayfirst=True)

In [9]:
prices.head()

  Ticker       date  close
0   AAME 2015-01-02   4.03
1   AAME 2015-01-05   4.01
2   AAME 2015-01-06   3.92
3   AAME 2015-01-07   3.92
4   AAME 2015-01-08   3.95

### Fundamentals Data

In [10]:
fundamentals= pd.read_csv('../dataset/fundamentals_filtered.csv')

In [11]:
# drop those with the names
names = ['TCON','TMBR', 'TAT', 'BSTC','ZSAN','RCKT','TAT','LLEXQ','WSTL','NTRP','JCAP','RKDA','RMNI','PATI','ZEUS']
fundamentals = fundamentals[~fundamentals['ticker'].isin(names)]
fundamentals

,datekey,ticker,dimension,calendardate,reportperiod,lastupdated,accoci,assets,assetsavg,assetsc,...,sharesbas,shareswa,shareswadil,sps,tangibles,taxassets,taxexp,taxliabilities,tbvps,workingcapital
23,2020-11-12,ZNOG,ARQ,2020-09-30,2020-09-30,2020-11-12,0.0,39391000.0,NaN,21994000.0,...,234621569.0,202877000.0,202877000.0,0.000,39391000.0,0.0,0.0,0.0,0.194,17276000.0
24,2020-08-10,ZNOG,ARQ,2020-06-30,2020-06-30,2020-11-12,0.0,27875000.0,NaN,10960000.0,...,205333221.0,172361000.0,172361000.0,0.000,27875000.0,0.0,0.0,0.0,0.162,6543000.0
25,2020-05-11,ZNOG,ARQ,2020-03-31,2020-03-31,2020-11-12,0.0,26176000.0,NaN,9649000.0,...,173367104.0,138813000.0,138813000.0,0.000,26176000.0,0.0,0.0,0.0,0.189,7832000.0
26,2020-03-27,ZNOG,ARQ,2019-12-31,2019-12-31,2020-11-12,0.0,18656000.0,NaN,6899000.0,...,161216944.0,81890000.0,81890000.0,0.000,18656000.0,0.0,0.0,0.0,0.228,5012000.0
27,2019-11-05,ZNOG,ARQ,2019-09-30,2019-09-30,2020-11-12,0.0,15585000.0,NaN,5789000.0,...,97617064.0,82001000.0,82001000.0,0.000,15585000.0,0.0,0.0,0.0,0.190,2987000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19384,2016-05-12,AAME,ARQ,2016-03-31,2016-03-31,2020-11-11,5561000.0,300133000.0,NaN,NaN,...,20419486.0,20419486.0,NaN,2.044,297589000.0,0.0,478000.0,175000.0,14.574,NaN
19385,2016-03-29,AAME,ARQ,2015-12-31,2015-12-31,2020-11-11,4584000.0,314603000.0,NaN,NaN,...,20394007.0,20394007.0,NaN,1.954,312059000.0,829000.0,30000.0,0.0,15.302,NaN
19386,2015-11-10,AAME,ARQ,2015-09-30,2015-09-30,2020-11-11,4807000.0,317203000.0,NaN,NaN,...,20547430.0,20547430.0,NaN,1.964,314659000.0,310000.0,127000.0,0.0,15.314,NaN
19387,2015-08-12,AAME,ARQ,2015-06-30,2015-06-30,2020-11-11,7235000.0,327225000.0,NaN,NaN,...,20592690.0,20592690.0,NaN,2.174,324681000.0,0.0,844000.0,338000.0,15.767,NaN
19388,2015-05-13,AAME,ARQ,2015-03-31,2015-03-31,2020-11-11,12379000.0,313185000.0,NaN,NaN,...,20573336.0,20573336.0,NaN,1.990,310641000.0,0.0,319000.0,3372000.0,15.099,NaN

In [12]:
fundamentals['calendardate'].unique()

array(['2020-09-30', '2020-06-30', '2020-03-31', '2019-12-31',
       '2019-09-30', '2019-06-30', '2019-03-31', '2018-12-31',
       '2018-09-30', '2018-06-30', '2018-03-31', '2017-12-31',
       '2017-09-30', '2017-06-30', '2017-03-31', '2016-12-31',
       '2016-09-30', '2016-06-30', '2016-03-31', '2015-12-31',
       '2015-09-30', '2015-06-30', '2015-03-31'], dtype=object)

In [13]:
#read in the earnings announcemnent date data
column_names = ['Ticker'] + list(fundamentals['calendardate'].unique())
ann_dates = pd.DataFrame(columns = column_names)
ann_dates['Ticker'] = fundamentals['ticker'].unique()

In [14]:
ann_dates

,Ticker,2020-09-30,2020-06-30,2020-03-31,2019-12-31,2019-09-30,2019-06-30,2019-03-31,2018-12-31,2018-09-30,...,2017-06-30,2017-03-31,2016-12-31,2016-09-30,2016-06-30,2016-03-31,2015-12-31,2015-09-30,2015-06-30,2015-03-31
0,ZNOG,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,ZIVO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,ZGNX,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,ZAGG,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,YEWB,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
824,ABMC,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
825,ABIO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
826,ABEO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
827,ABCP,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
828,AAME,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [15]:
ann_per_ticker = fundamentals.groupby('ticker')['datekey'].apply(list).to_dict()

In [16]:
ann_per_ticker_transposed = pd.DataFrame(ann_per_ticker).transpose()
ann_per_ticker_transposed.reset_index(inplace=True)
ann_per_ticker_transposed

# ann_per_ticker_transposed.rename(columns = {'index':'Ticker'})

,index,0,1,2,3,4,5,6,7,8,...,13,14,15,16,17,18,19,20,21,22
0,AAME,2020-11-10,2020-08-11,2020-05-11,2020-03-24,2019-11-12,2019-08-13,2019-05-13,2019-04-01,2018-11-13,...,2017-08-14,2017-05-12,2017-03-24,2016-11-14,2016-08-12,2016-05-12,2016-03-29,2015-11-10,2015-08-12,2015-05-13
1,ABCP,2020-11-10,2020-08-10,2020-05-07,2020-03-25,2019-11-12,2019-08-12,2019-05-13,2019-03-27,2018-11-09,...,2017-08-11,2017-05-11,2017-03-30,2016-11-08,2016-08-11,2016-05-12,2016-03-29,2015-11-10,2015-08-12,2015-05-13
2,ABEO,2020-11-09,2020-08-10,2020-05-06,2020-03-16,2019-11-12,2019-08-09,2019-05-10,2019-03-18,2018-11-09,...,2017-08-14,2017-05-15,2017-03-30,2016-11-14,2016-08-15,2016-05-16,2016-03-30,2015-11-16,2015-08-14,2015-05-14
3,ABIO,2020-11-02,2020-08-05,2020-05-06,2020-02-18,2019-11-06,2019-08-01,2019-05-08,2019-02-27,2018-11-14,...,2017-08-03,2017-05-15,2017-03-21,2016-11-14,2016-08-09,2016-05-11,2016-03-17,2015-11-12,2015-08-11,2015-05-12
4,ABMC,2020-11-16,2020-09-15,2020-07-31,2020-06-26,2019-11-14,2019-08-14,2019-05-20,2019-04-16,2018-11-13,...,2017-08-14,2017-05-15,2017-03-31,2016-11-14,2016-08-15,2016-05-16,2016-03-30,2015-11-16,2015-08-14,2015-05-15
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
824,YEWB,2020-11-13,2020-08-14,2020-06-29,2020-05-14,2019-11-14,2019-08-13,2019-05-22,2019-05-07,2018-11-19,...,2017-08-14,2017-05-15,2017-03-31,2016-11-14,2016-08-15,2016-05-16,2016-03-30,2015-11-16,2015-08-18,2015-05-14
825,ZAGG,2020-11-09,2020-08-04,2020-05-28,2020-03-16,2019-11-07,2019-08-07,2019-05-08,2019-03-14,2018-11-07,...,2017-08-03,2017-05-04,2017-03-09,2016-11-02,2016-08-03,2016-05-10,2016-03-08,2015-11-04,2015-08-05,2015-05-06
826,ZGNX,2020-11-09,2020-08-06,2020-05-06,2020-03-02,2019-11-07,2019-08-06,2019-05-09,2019-02-28,2018-11-08,...,2017-08-08,2017-05-04,2017-03-10,2016-11-08,2016-08-09,2016-05-10,2016-03-15,2015-11-09,2015-08-10,2015-05-11
827,ZIVO,2020-11-12,2020-08-13,2020-05-11,2020-03-26,2019-10-28,2019-08-07,2019-05-13,2019-02-12,2018-11-14,...,2017-08-11,2017-05-12,2017-03-31,2016-11-14,2016-08-12,2016-05-13,2016-03-29,2015-11-13,2015-08-13,2015-05-13
828,ZNOG,2020-11-12,2020-08-10,2020-05-11,2020-03-27,2019-11-05,2019-08-07,2019-05-14,2019-03-08,2018-11-08,...,2017-08-11,2017-05-09,2017-03-14,2016-11-10,2016-08-09,2016-05-16,2016-03-15,2015-11-10,2015-08-03,2015-05-07

In [17]:
#change the column names
ann_per_ticker_transposed.rename(columns=dict(zip(ann_per_ticker_transposed.columns,column_names)), inplace = True)
# df.rename(columns=dict(zip(df.columns,l)))

#the column names are the calendar date that the earnings are supposed to represent, 
#and the dates below are the announcement dates
ann_per_ticker_transposed.head()

,Ticker,2020-09-30,2020-06-30,2020-03-31,2019-12-31,2019-09-30,2019-06-30,2019-03-31,2018-12-31,2018-09-30,...,2017-06-30,2017-03-31,2016-12-31,2016-09-30,2016-06-30,2016-03-31,2015-12-31,2015-09-30,2015-06-30,2015-03-31
0,AAME,2020-11-10,2020-08-11,2020-05-11,2020-03-24,2019-11-12,2019-08-13,2019-05-13,2019-04-01,2018-11-13,...,2017-08-14,2017-05-12,2017-03-24,2016-11-14,2016-08-12,2016-05-12,2016-03-29,2015-11-10,2015-08-12,2015-05-13
1,ABCP,2020-11-10,2020-08-10,2020-05-07,2020-03-25,2019-11-12,2019-08-12,2019-05-13,2019-03-27,2018-11-09,...,2017-08-11,2017-05-11,2017-03-30,2016-11-08,2016-08-11,2016-05-12,2016-03-29,2015-11-10,2015-08-12,2015-05-13
2,ABEO,2020-11-09,2020-08-10,2020-05-06,2020-03-16,2019-11-12,2019-08-09,2019-05-10,2019-03-18,2018-11-09,...,2017-08-14,2017-05-15,2017-03-30,2016-11-14,2016-08-15,2016-05-16,2016-03-30,2015-11-16,2015-08-14,2015-05-14
3,ABIO,2020-11-02,2020-08-05,2020-05-06,2020-02-18,2019-11-06,2019-08-01,2019-05-08,2019-02-27,2018-11-14,...,2017-08-03,2017-05-15,2017-03-21,2016-11-14,2016-08-09,2016-05-11,2016-03-17,2015-11-12,2015-08-11,2015-05-12
4,ABMC,2020-11-16,2020-09-15,2020-07-31,2020-06-26,2019-11-14,2019-08-14,2019-05-20,2019-04-16,2018-11-13,...,2017-08-14,2017-05-15,2017-03-31,2016-11-14,2016-08-15,2016-05-16,2016-03-30,2015-11-16,2015-08-14,2015-05-15

# Preprocessing for Backtesting

In [18]:
sue_ticker_index = sue.copy()
# sue_ticker_index.set_index('Ticker')

In [19]:
# reset index and change the name to QtrEnd
# cutoff.reset_index(inplace=True)
cutoff.rename(columns = {'Unnamed: 0':'QtrEnd'}, inplace = True)

In [20]:
cutoff.head()

,QtrEnd,10,15,20,25,30,40,50,60,70,75,80,85,90
0,2020-03-31,-3.564696,-2.785541,-2.238445,-1.726030,-1.333524,-0.772274,-0.163857,0.381893,0.938098,1.198657,1.510083,1.965605,2.454226
1,2019-12-31,-2.110828,-1.410253,-1.093586,-0.773738,-0.448948,0.079900,0.589183,1.103181,1.545486,1.815404,2.139856,2.379102,2.662984
2,2019-09-30,-1.617063,-1.244536,-0.936345,-0.640495,-0.367696,0.122470,0.619369,1.109803,1.532296,1.810733,2.102072,2.432977,2.838799
3,2019-06-30,-1.497825,-1.118737,-0.803735,-0.495148,-0.222220,0.217962,0.574483,0.957188,1.386805,1.584325,1.877683,2.262846,2.636423
4,2019-03-31,-1.501021,-1.106272,-0.840493,-0.528025,-0.287363,0.165315,0.611116,0.970800,1.478091,1.617331,1.904388,2.237324,2.623735

In [21]:
sue_ticker_index.head()

,Ticker,2020-09-30,2020-06-30,2020-03-31,2019-12-31,2019-09-30,2019-06-30,2019-03-31,2018-12-31,2018-09-30,2018-06-30,2018-03-31,2017-12-31,2017-09-30,2017-06-30
0,ZSAN,3.641045,4.221555,1.989709,2.251946,2.537229,2.747534,2.828003,3.022944,3.332997,3.755863,2.880589,3.354443,3.650315,5.018590
1,ZNOG,1.147121,0.848846,0.816676,0.380124,0.004283,-0.110571,-0.411498,-10.173853,2.071430,1.086995,-1.448836,1.325810,-0.204124,-3.130094
2,ZIVO,1.852141,3.485026,2.455164,2.763033,2.607801,1.372527,-0.618590,-0.453632,-3.058186,-1.593703,-3.181981,-4.110713,-2.428571,0.476604
3,ZGNX,0.086983,-0.160761,-0.317842,-0.847280,-16.450464,1.447635,1.275126,2.077907,-0.721773,-0.460095,-1.436718,-2.576697,-6.920321,-1.793685
4,ZEUS,-1.966852,-3.198508,-2.158503,-2.150177,-1.360070,-0.805991,-0.751397,0.001566,2.796222,4.612399,2.566677,2.018295,1.628601,2.291578

In [22]:
ann_dates = ann_per_ticker_transposed

In [23]:
ann_dates.head()

,Ticker,2020-09-30,2020-06-30,2020-03-31,2019-12-31,2019-09-30,2019-06-30,2019-03-31,2018-12-31,2018-09-30,...,2017-06-30,2017-03-31,2016-12-31,2016-09-30,2016-06-30,2016-03-31,2015-12-31,2015-09-30,2015-06-30,2015-03-31
0,AAME,2020-11-10,2020-08-11,2020-05-11,2020-03-24,2019-11-12,2019-08-13,2019-05-13,2019-04-01,2018-11-13,...,2017-08-14,2017-05-12,2017-03-24,2016-11-14,2016-08-12,2016-05-12,2016-03-29,2015-11-10,2015-08-12,2015-05-13
1,ABCP,2020-11-10,2020-08-10,2020-05-07,2020-03-25,2019-11-12,2019-08-12,2019-05-13,2019-03-27,2018-11-09,...,2017-08-11,2017-05-11,2017-03-30,2016-11-08,2016-08-11,2016-05-12,2016-03-29,2015-11-10,2015-08-12,2015-05-13
2,ABEO,2020-11-09,2020-08-10,2020-05-06,2020-03-16,2019-11-12,2019-08-09,2019-05-10,2019-03-18,2018-11-09,...,2017-08-14,2017-05-15,2017-03-30,2016-11-14,2016-08-15,2016-05-16,2016-03-30,2015-11-16,2015-08-14,2015-05-14
3,ABIO,2020-11-02,2020-08-05,2020-05-06,2020-02-18,2019-11-06,2019-08-01,2019-05-08,2019-02-27,2018-11-14,...,2017-08-03,2017-05-15,2017-03-21,2016-11-14,2016-08-09,2016-05-11,2016-03-17,2015-11-12,2015-08-11,2015-05-12
4,ABMC,2020-11-16,2020-09-15,2020-07-31,2020-06-26,2019-11-14,2019-08-14,2019-05-20,2019-04-16,2018-11-13,...,2017-08-14,2017-05-15,2017-03-31,2016-11-14,2016-08-15,2016-05-16,2016-03-30,2015-11-16,2015-08-14,2015-05-15

In [24]:
for i in ann_dates.columns.tolist()[1:]:
    print(i)
    ann_dates[i]= pd.to_datetime(ann_dates[i],dayfirst=True)
print(ann_dates[i])

2020-09-30
2020-06-30
2020-03-31
2019-12-31
2019-09-30
2019-06-30
2019-03-31
2018-12-31
2018-09-30
2018-06-30
2018-03-31
2017-12-31
2017-09-30
2017-06-30
2017-03-31
2016-12-31
2016-09-30
2016-06-30
2016-03-31
2015-12-31
2015-09-30
2015-06-30
2015-03-31
0     2015-05-13
1     2015-05-13
2     2015-05-14
3     2015-05-12
4     2015-05-15
         ...
824   2015-05-14
825   2015-05-06
826   2015-05-11
827   2015-05-13
828   2015-05-07
Name: 2015-03-31, Length: 829, dtype: datetime64[ns]

In [25]:
ann_dates

,Ticker,2020-09-30,2020-06-30,2020-03-31,2019-12-31,2019-09-30,2019-06-30,2019-03-31,2018-12-31,2018-09-30,...,2017-06-30,2017-03-31,2016-12-31,2016-09-30,2016-06-30,2016-03-31,2015-12-31,2015-09-30,2015-06-30,2015-03-31
0,AAME,2020-11-10,2020-08-11,2020-05-11,2020-03-24,2019-11-12,2019-08-13,2019-05-13,2019-04-01,2018-11-13,...,2017-08-14,2017-05-12,2017-03-24,2016-11-14,2016-08-12,2016-05-12,2016-03-29,2015-11-10,2015-08-12,2015-05-13
1,ABCP,2020-11-10,2020-08-10,2020-05-07,2020-03-25,2019-11-12,2019-08-12,2019-05-13,2019-03-27,2018-11-09,...,2017-08-11,2017-05-11,2017-03-30,2016-11-08,2016-08-11,2016-05-12,2016-03-29,2015-11-10,2015-08-12,2015-05-13
2,ABEO,2020-11-09,2020-08-10,2020-05-06,2020-03-16,2019-11-12,2019-08-09,2019-05-10,2019-03-18,2018-11-09,...,2017-08-14,2017-05-15,2017-03-30,2016-11-14,2016-08-15,2016-05-16,2016-03-30,2015-11-16,2015-08-14,2015-05-14
3,ABIO,2020-11-02,2020-08-05,2020-05-06,2020-02-18,2019-11-06,2019-08-01,2019-05-08,2019-02-27,2018-11-14,...,2017-08-03,2017-05-15,2017-03-21,2016-11-14,2016-08-09,2016-05-11,2016-03-17,2015-11-12,2015-08-11,2015-05-12
4,ABMC,2020-11-16,2020-09-15,2020-07-31,2020-06-26,2019-11-14,2019-08-14,2019-05-20,2019-04-16,2018-11-13,...,2017-08-14,2017-05-15,2017-03-31,2016-11-14,2016-08-15,2016-05-16,2016-03-30,2015-11-16,2015-08-14,2015-05-15
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
824,YEWB,2020-11-13,2020-08-14,2020-06-29,2020-05-14,2019-11-14,2019-08-13,2019-05-22,2019-05-07,2018-11-19,...,2017-08-14,2017-05-15,2017-03-31,2016-11-14,2016-08-15,2016-05-16,2016-03-30,2015-11-16,2015-08-18,2015-05-14
825,ZAGG,2020-11-09,2020-08-04,2020-05-28,2020-03-16,2019-11-07,2019-08-07,2019-05-08,2019-03-14,2018-11-07,...,2017-08-03,2017-05-04,2017-03-09,2016-11-02,2016-08-03,2016-05-10,2016-03-08,2015-11-04,2015-08-05,2015-05-06
826,ZGNX,2020-11-09,2020-08-06,2020-05-06,2020-03-02,2019-11-07,2019-08-06,2019-05-09,2019-02-28,2018-11-08,...,2017-08-08,2017-05-04,2017-03-10,2016-11-08,2016-08-09,2016-05-10,2016-03-15,2015-11-09,2015-08-10,2015-05-11
827,ZIVO,2020-11-12,2020-08-13,2020-05-11,2020-03-26,2019-10-28,2019-08-07,2019-05-13,2019-02-12,2018-11-14,...,2017-08-11,2017-05-12,2017-03-31,2016-11-14,2016-08-12,2016-05-13,2016-03-29,2015-11-13,2015-08-13,2015-05-13
828,ZNOG,2020-11-12,2020-08-10,2020-05-11,2020-03-27,2019-11-05,2019-08-07,2019-05-14,2019-03-08,2018-11-08,...,2017-08-11,2017-05-09,2017-03-14,2016-11-10,2016-08-09,2016-05-16,2016-03-15,2015-11-10,2015-08-03,2015-05-07

In [26]:
prices

        Ticker       date  close
0         AAME 2015-01-02  4.030
1         AAME 2015-01-05  4.010
2         AAME 2015-01-06  3.920
3         AAME 2015-01-07  3.920
4         AAME 2015-01-08  3.950
...        ...        ...    ...
1264593   ZNOG 2020-12-14  1.000
1264594   ZNOG 2020-12-15  0.810
1264595   ZNOG 2020-12-16  0.910
1264596   ZNOG 2020-12-17  0.902
1264597   ZNOG 2020-12-18  0.860

[1245593 rows x 3 columns]

# Portfolio Backtesting

In [27]:
import datetime as datetime 

mod_prices=prices.copy()
start=datetime.datetime(2015, 1, 2)
end=datetime.datetime(2020, 12, 18)

#for i in range(len(df1)):
#    if i%10000==0:
#        print(i)
#    if df1.iloc[i]['date']<start or df1.iloc[i]['date']>end:
#        indices.append(i)
#df1.drop(df1.index[indices],inplace=True)


#indices=[]

mod_prices = mod_prices[mod_prices['date']>=start]
mod_prices = mod_prices[mod_prices['date']<=end]


#print(len(df1))
#winsound.Beep(500,1000)
mod_prices.reset_index(inplace=True)
mod_prices.drop('index',axis=1,inplace=True)
#df1.drop('index',axis=1,inplace=True)
#df1.drop('PX_VOLUME',axis=1,inplace=True)

In [28]:
mod_prices = mod_prices.rename(columns={'close': 'PX_LAST'})

In [29]:
len(mod_prices.Ticker.unique())

829

In [30]:
# we append out those with lesser dates
df_s=mod_prices.groupby('Ticker').count()
df_s.reset_index(inplace=True)

max=0
for i in range (len(df_s)):
    if df_s.iloc[i]['date']>max:
        max=df_s.iloc[i]['date']
#print(max)

less_dates=[]
for i in range (len(df_s)):
    if df_s.iloc[i]['date']!=max:
        #print (df_s.iloc[i]['Ticker'])
        #print (df_s.iloc[i]['date'])
        less_dates.append(df_s.iloc[i]['Ticker'])
print(less_dates)

for j in less_dates:
    mod_prices = mod_prices[mod_prices['Ticker']!=j]

['AJX', 'BLPH', 'CDTX', 'FNWB', 'HTGM', 'ICBK', 'KALV', 'OPGN']

In [31]:
len(fundamentals['ticker'].unique())

829

In [32]:
len(less_dates)
# less_dates contains those with less dates than we proposed above

8

In [33]:
len(mod_prices['Ticker'].unique())

821

In [34]:
sue

,Ticker,2020-09-30,2020-06-30,2020-03-31,2019-12-31,2019-09-30,2019-06-30,2019-03-31,2018-12-31,2018-09-30,2018-06-30,2018-03-31,2017-12-31,2017-09-30,2017-06-30
0,ZSAN,3.641045e+00,4.221555,1.989709,2.251946,2.537229,2.747534,2.828003,3.022944,3.332997,3.755863,2.880589,3.354443,3.650315,5.018590
1,ZNOG,1.147121e+00,0.848846,0.816676,0.380124,0.004283,-0.110571,-0.411498,-10.173853,2.071430,1.086995,-1.448836,1.325810,-0.204124,-3.130094
2,ZIVO,1.852141e+00,3.485026,2.455164,2.763033,2.607801,1.372527,-0.618590,-0.453632,-3.058186,-1.593703,-3.181981,-4.110713,-2.428571,0.476604
3,ZGNX,8.698323e-02,-0.160761,-0.317842,-0.847280,-16.450464,1.447635,1.275126,2.077907,-0.721773,-0.460095,-1.436718,-2.576697,-6.920321,-1.793685
4,ZEUS,-1.966852e+00,-3.198508,-2.158503,-2.150177,-1.360070,-0.805991,-0.751397,0.001566,2.796222,4.612399,2.566677,2.018295,1.628601,2.291578
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
837,ABMC,3.583229e-16,0.959024,-0.442627,0.221313,1.180338,1.237179,-1.549193,-1.857143,-1.000000,0.142857,-2.065591,-0.959024,0.442627,-0.516398
838,ABIO,3.479518e+00,2.943787,2.952742,2.892162,3.050012,2.925279,2.971252,3.259067,3.621325,3.727505,3.681175,0.057834,-1.359271,-1.150707
839,ABEO,3.207940e+00,1.825819,-2.954727,-1.286875,-2.331085,-4.003191,-3.359117,-4.770359,-4.705104,-2.425419,-0.568962,-1.443995,0.013325,-1.134262
840,ABCP,-1.695243e+00,-0.385257,-1.670991,-1.699744,0.987772,0.787180,0.660585,0.507498,0.240526,0.032726,-0.067631,0.190862,-180.215763,0.412393
841,AAME,3.598881e-01,0.553360,-2.409900,0.036662,-0.756285,-1.682371,1.609393,-0.204969,0.117901,0.788824,-5.914581,3.854932,0.959910,-0.340068

In [35]:
#qtr end based on which to form the portfolio, example: Jun-19, Mar-19, Dec-18, Sep-18
#percentile is the long cutoff (number, not a string)
def port_form (qtr_end,percentile):
    long_cutoff = 0
    short_cutoff = 0
    #print (cutoff.iloc[2]['QtrEnd'])
    #print(qtr_end)
    for i in range(len(cutoff)):
        if cutoff.iloc[i]['QtrEnd']==qtr_end:
            long_cutoff = cutoff.iloc[i-1][str(percentile)]
            short_cutoff = cutoff.iloc[i-1][str(100-percentile)]
    long_st=[]
    short_st=[]
    for i in range(len(sue)):
        if sue.iloc[i][qtr_end]>=long_cutoff:
            long_st.append(sue.iloc[i]['Ticker'])
        elif sue.iloc[i][qtr_end]<=short_cutoff:
            short_st.append(sue.iloc[i]['Ticker'])
    return long_st, short_st

In [36]:
def announce_date (ticker,qtr_end):
    ann_date = 0
    qtr_dt = pd.to_datetime(qtr_end)
    # if real stock is entered and if date is really at quarter end, if thats true, announcement date
    if (ticker in ann_dates['Ticker'].values)&(((qtr_dt.day == 30)& (qtr_dt.month in [6,9])) 
                                        or ((qtr_dt.day == 31)& (qtr_dt.month in [3,12]))):
        ann_date = ann_dates.loc[ann_dates['Ticker']==ticker].iloc[0][qtr_end]
#         print(temp)
    else:
        print('not qtr end or not valid stock')
        return None
    return ann_date

In [37]:
type(mod_prices.iloc[0]['date'])

pandas._libs.tslibs.timestamps.Timestamp

In [38]:
mod_prices

        Ticker       date  PX_LAST
0         AAME 2015-01-02    4.030
1         AAME 2015-01-05    4.010
2         AAME 2015-01-06    3.920
3         AAME 2015-01-07    3.920
4         AAME 2015-01-08    3.950
...        ...        ...      ...
1245588   ZNOG 2020-12-14    1.000
1245589   ZNOG 2020-12-15    0.810
1245590   ZNOG 2020-12-16    0.910
1245591   ZNOG 2020-12-17    0.902
1245592   ZNOG 2020-12-18    0.860

[1233963 rows x 3 columns]

In [39]:
prices

        Ticker       date  close
0         AAME 2015-01-02  4.030
1         AAME 2015-01-05  4.010
2         AAME 2015-01-06  3.920
3         AAME 2015-01-07  3.920
4         AAME 2015-01-08  3.950
...        ...        ...    ...
1264593   ZNOG 2020-12-14  1.000
1264594   ZNOG 2020-12-15  0.810
1264595   ZNOG 2020-12-16  0.910
1264596   ZNOG 2020-12-17  0.902
1264597   ZNOG 2020-12-18  0.860

[1245593 rows x 3 columns]

In [40]:
def trade (ticker,ann_date,SL=-0.05,TP=0.1,ndays=40,posn='long'):
    #posn = position.copy()
    #print (ticker)     
    print(ticker)
    
    names = []

    i =0
    #this is correct, i should put an i = 0 here
    price = mod_prices[mod_prices['Ticker']==ticker]
    price.reset_index(inplace=True)
   
    #before the for loop, i is '2017-06-30'
    
    for i in range (len(price)):
        # once it goes into the for loop, i is 0 and then loop into 1,2,3,...
#         print(i)
        if price.iloc[i]['date']>=ann_date:
            break
            
#     print(f'last 1 i: {i}')

#     print(i) # i should be 912 here, but its 0 i think
    start = price.iloc[i]['date']
#     print(f'last 2 i: {i}')

    #print(start)
    end = price.iloc[i+ int(ndays)]['date']
    #print(end)
    
    price = price[price['date']>=start]
    price = price[price['date']<end]
    
    price.reset_index(inplace=True)
    price.drop('index',axis=1,inplace=True)
#     print(price)
    
#     print(f'last 3 i: {i}')

    
    buy_price = price.iloc[0]['PX_LAST']
    trade_end = ''
    for i in range(1,len(price)):
        if posn == 'long':
            if (price.iloc[i]['PX_LAST']-buy_price)/buy_price<=SL:
                sell_price = price.iloc[i]['PX_LAST']
                posn = 'squared off'
                trade_end = 'SLH'
                profit = (sell_price-buy_price)/buy_price
                #i believe that profit is in percentage
                break
            elif (price.iloc[i]['PX_LAST']-buy_price)/buy_price>=TP:
                sell_price = price.iloc[i]['PX_LAST']
                posn = 'squared off'
                trade_end = 'PB'
                profit = (sell_price-buy_price)/buy_price
                break
        if posn == 'short':
            if (-(price.iloc[i]['PX_LAST']-buy_price))/buy_price<=SL:
                sell_price = price.iloc[i]['PX_LAST']
                posn = 'squared off'
                trade_end = 'SLH'
                profit = (-(sell_price-buy_price))/buy_price
                break
            elif (-(price.iloc[i]['PX_LAST']-buy_price))/buy_price>=TP:
                sell_price = price.iloc[i]['PX_LAST']
                posn = 'squared off'
                trade_end = 'PB'
                profit = (-(sell_price-buy_price))/buy_price
                break
    
        if posn!='squared off':
            sell_price = price.iloc[len(price)-1]['PX_LAST']
            trade_end = 'PSO'
            if posn=='long':
                profit = (sell_price-buy_price)/buy_price
            else:
                profit = (-(sell_price-buy_price))/buy_price
    
#     print(f'last 4 i: {i}')
#     print(ticker)
                    
    return buy_price, sell_price, profit, trade_end

In [41]:
announce_date('ZNOG','2019-09-30')

Timestamp('2019-11-05 00:00:00')

In [42]:
a,b,c,d= trade ('ZNOG',announce_date('ZNOG','2019-09-30'))

ZNOG

In [43]:
long_st,short_st=port_form('2020-09-30',90)

In [44]:
long_st

['ZSAN',
 'ZNOG',
 'ZIVO',
 'ZGNX',
 'YEWB',
 'XTNT',
 'XSPA',
 'XENE',
 'WYY',
 'WWR',
 'WVVI',
 'WSTL',
 'WHLR',
 'WHF',
 'WATT',
 'VXRT',
 'VUZI',
 'VOXX',
 'VNRX',
 'VIVE',
 'VIRC',
 'VGZ',
 'VCRA',
 'VCEL',
 'VBTX',
 'VBFC',
 'VASO',
 'VALU',
 'UWHR',
 'UUU',
 'UTI',
 'USNU',
 'USIO',
 'URG',
 'UNB',
 'UMH',
 'UCTT',
 'UBOH',
 'UBCP',
 'TSRI',
 'TSBK',
 'TRXC',
 'TRVN',
 'TOMZ',
 'TOFB',
 'TNXP',
 'TNLX',
 'TMQ',
 'TIPT',
 'TIKK',
 'THMO',
 'TGLS',
 'TGHI',
 'TGEN',
 'TENX',
 'TCON',
 'TBK',
 'SYN',
 'SWKH',
 'SUWN',
 'SUNW',
 'SUNS',
 'SUMR',
 'STRT',
 'STRM',
 'STCN',
 'SSSS',
 'SRT',
 'SRNA',
 'SRGZ',
 'SPRT',
 'SPND',
 'SPKE',
 'SOTK',
 'SONN',
 'SNSS',
 'SNGX',
 'SNFCA',
 'SNCA',
 'SMTX',
 'SMTI',
 'SMMF',
 'SMIT',
 'SMDM',
 'SKY',
 'SIMP',
 'SHYF',
 'SHSP',
 'SGMA',
 'SGLB',
 'SGC',
 'SFBC',
 'SESN',
 'SENEA',
 'SEEL',
 'SCYX',
 'SCON',
 'SBFG',
 'SAR',
 'SAL',
 'RSSS',
 'RNWK',
 'RMNI',
 'RM',
 'RILY',
 'RIBT',
 'RHE',
 'RESN',
 'REPH',
 'RELV',
 'REFR',
 'RCKY',
 'RAND',
 'QUIK',
 'QTXB',
 'QTNT',
 'QSEP',
 'QNBC',
 'QCRH',
 'PWOD',
 'PWFL',
 'PURE',
 'PULM',
 'PTMN',
 'PSTV',
 'PSTI',
 'PRTS',
 'PRPO',
 'PRPH',
 'PROV',
 'PRDO',
 'PPSI',
 'PMBC',
 'PLXP',
 'PLX',
 'PLPC',
 'PFMT',
 'PFLT',
 'PEYE',
 'PESI',
 'PEIX',
 'PED',
 'PEBK',
 'PDEX',
 'PCYN',
 'PCTI',
 'PBHC',
 'PAR',
 'OXBR',
 'OVTZ',
 'ORRF',
 'ORN',
 'ORMP',
 'ORGS',
 'ORC',
 'OPTT',
 'OPHC',
 'OPGN',
 'OPCH',
 'ONTX',
 'ONCT',
 'ONCS',
 'OMTK',
 'OFS',
 'OFED',
 'OESX',
 'ODC',
 'OCUP',
 'OBCI',
 'NWIN',
 'NVUS',
 'NURO',
 'NTRP',
 'NTIP',
 'NSYS',
 'NSTG',
 'NSPR',
 'NRIM',
 'NMRD',
 'NLTX',
 'NLST',
 'NIMU',
 'NICK',
 'NERV',
 'NCBS',
 'NBY',
 'NAVB',
 'NATR',
 'NANX',
 'MX',
 'MVIS',
 'MVBF',
 'MTEX',
 'MTEM',
 'MRNS',
 'MRMD',
 'MRCC',
 'MPB',
 'MOSY',
 'MOJO',
 'MNTX',
 'MNOV',
 'MN',
 'MLSS',
 'MITK',
 'MHH',
 'MGEN',
 'MFNC',
 'MEIP',
 'MDVL',
 'MDLY',
 'MCEP',
 'MCCX',
 'MBOT',
 'MATN',
 'MARK',
 'MAGE',
 'LYTS',
 'LWLG',
 'LUVU',
 'LTBR',
 'LSBK',
 'LPTH',
 'LPCN',
 'LODE',
 'LMB',
 'LMAT',
 'LEU',
 'LEDS',
 'LEAT',
 'LEAF',
 'LCUT',
 'LAWS',
 'KTYB',
 'KTCC',
 'KSPN',
 'KOSS',
 'KIN',
 'JUVF',
 'JSDA',
 'JOUT',
 'JCTCF',
 'JCS',
 'JAKK',
 'ITP',
 'ITIC',
 'ITI',
 'ISR',
 'IROQ',
 'IRIX',
 'IPWR',
 'IPDN',
 'INTT',
 'INTI',
 'INTG',
 'INS',
 'INOD',
 'INFU',
 'INBK',
 'IMH',
 'IMBI',
 'III',
 'IESC',
 'IDN',
 'ICCC',
 'ICAD',
 'IAIC',
 'HWBK',
 'HTGM',
 'HSTO',
 'HQI',
 'HPTO',
 'HMNF',
 'HMG',
 'HGBL',
 'HFBL',
 'HEPA',
 'HEAR',
 'HBP',
 'HBNC',
 'GV',
 'GTIM',
 'GROW',
 'GORO',
 'GNSS',
 'GNCA',
 'GLYC',
 'GLGI',
 'GLG',
 'GLBZ',
 'GLAD',
 'GIGA',
 'GHM',
 'GFN',
 'GCBC',
 'GAIA',
 'FVE',
 'FTLF',
 'FTEK',
 'FSBW',
 'FORD',
 'FNWB',
 'FNLC',
 'FMNB',
 'FMBM',
 'FMAO',
 'FLXT',
 'FLXS',
 'FLL',
 'FFWM',
 'FEIM',
 'FDUS',
 'FDBC',
 'FCAP',
 'FBSS',
 'FALC',
 'EYPT',
 'EXEO',
 'EVOL',
 'EVFM',
 'ESXB',
 'ESSA',
 'ESCA',
 'ERII',
 'ENSV',
 'ENG',
 'ENBP',
 'EMYB',
 'EMKR',
 'EMGCQ',
 'EMCF',
 'ELOX',
 'ELMD',
 'EKSO',
 'EGAN',
 'EFSI',
 'ECOM',
 'ECIA',
 'EBTC',
 'EBMT',
 'EARN',
 'DXYN',
 'DWSN',
 'DVD',
 'DSS',
 'DSNY',
 'DRAD',
 'DMRC',
 'DLYT',
 'DLHC',
 'DJCO',
 'DIT',
 'DGLY',
 'DGII',
 'DFFN',
 'DARE',
 'CZWI',
 'CYTR',
 'CYCC',
 'CYBE',
 'CXDO',
 'CWST',
 'CWBC',
 'CVV',
 'CUTR',
 'CTSO',
 'CTIB',
 'CTG',
 'CSBB',
 'CRWS',
 'CRVW',
 'CRMZ',
 'CRMD',
 'CRGS',
 'CREX',
 'CRDF',
 'CRAI',
 'CPTP',
 'CPTA',
 'CPST',
 'CPSH',
 'CPRX',
 'CPIX',
 'CPAH',
 'COMS',
 'COHU',
 'COHN',
 'COFS',
 'CNFN',
 'CNET',
 'CNBKA',
 'CMXC',
 'CMT',
 'CLRO',
 'CLRB',
 'CLIR',
 'CLFD',
 'CLDB',
 'CLCT',
 'CLBS',
 'CKX',
 'CIZN',
 'CIVB',
 'CIO',
 'CHMI',
 'CGIX',
 'CFFI',
 'CFBK',
 'CDZI',
 'CDXC',
 'CDTX',
 'CDNA',
 'CDMO',
 'CCUR',
 'CCEL',
 'CCBG',
 'CBLI',
 'CBKM',
 'CBIO',
 'CBAY',
 'CASH',
 'CARV',
 'CARA',
 'CAPR',
 'CALA',
 'CAC',
 'CAAS',
 'BXC',
 'BWEN',
 'BTN',
 'BSTG',
 'BSRR',
 'BSQR',
 'BRN',
 'BPTH',
 'BLBD',
 'BKTI',
 'BKEP',
 'BIOL',
 'BIOC',
 'BICX',
 'BELFA',
 'BDGE',
 'BCOV',
 'BCLI',
 'BCBP',
 'BBW',
 'BBI',
 'AXR',
 'AXGN',
 'AWX',
 'AWH',
 'AVNW',
 'AUTO',
 'ATRS',
 'ATNM',
 'ATLO',
 'ATLC',
 'ASYS',
 'ASTC',
 'ASPN',
 'ASMB',
 'ARTW',
 'ARDX',
 'APT',
 'APDN',
 'AP',
 'AOSL',
 'ANDR',
 'AMRK',
 'AMRB',
 'AMNB',
 'ALSK',
 'ALDX',
 'AKBA',
 'AIM',
 'AHPI',
 'AHH',
 'AGYS',
 'AEY',
 'AERI',
 'AEHR',
 'AE',
 'ADMT',
 'ADMP',
 'ADMA',
 'ACUR',
 'ACU',
 'ACRX',
 'ACHV',
 'ACFN',
 'ACER',
 'ABMC',
 'ABIO',
 'ABEO',
 'AAME']

In [45]:
qtr_end_list=ann_dates.columns.tolist()[1:-9]
qtr_end_list

['2020-09-30',
 '2020-06-30',
 '2020-03-31',
 '2019-12-31',
 '2019-09-30',
 '2019-06-30',
 '2019-03-31',
 '2018-12-31',
 '2018-09-30',
 '2018-06-30',
 '2018-03-31',
 '2017-12-31',
 '2017-09-30',
 '2017-06-30']

In [46]:
# qtr_end_list has to end before 2017-03-31, last entry should be 2017-06-30
long=[]
short=[]
for i in qtr_end_list:
    lo,sho = port_form (i,90)
    long.append(lo)
    short.append(sho)
#     print(f'{long}\n')

In [47]:
long_port = dict(zip(qtr_end_list, long)) 
short_port = dict(zip(qtr_end_list, short))

In [48]:
long_port

{'2020-09-30': ['ZSAN',
  'ZNOG',
  'ZIVO',
  'ZGNX',
  'YEWB',
  'XTNT',
  'XSPA',
  'XENE',
  'WYY',
  'WWR',
  'WVVI',
  'WSTL',
  'WHLR',
  'WHF',
  'WATT',
  'VXRT',
  'VUZI',
  'VOXX',
  'VNRX',
  'VIVE',
  'VIRC',
  'VGZ',
  'VCRA',
  'VCEL',
  'VBTX',
  'VBFC',
  'VASO',
  'VALU',
  'UWHR',
  'UUU',
  'UTI',
  'USNU',
  'USIO',
  'URG',
  'UNB',
  'UMH',
  'UCTT',
  'UBOH',
  'UBCP',
  'TSRI',
  'TSBK',
  'TRXC',
  'TRVN',
  'TOMZ',
  'TOFB',
  'TNXP',
  'TNLX',
  'TMQ',
  'TIPT',
  'TIKK',
  'THMO',
  'TGLS',
  'TGHI',
  'TGEN',
  'TENX',
  'TCON',
  'TBK',
  'SYN',
  'SWKH',
  'SUWN',
  'SUNW',
  'SUNS',
  'SUMR',
  'STRT',
  'STRM',
  'STCN',
  'SSSS',
  'SRT',
  'SRNA',
  'SRGZ',
  'SPRT',
  'SPND',
  'SPKE',
  'SOTK',
  'SONN',
  'SNSS',
  'SNGX',
  'SNFCA',
  'SNCA',
  'SMTX',
  'SMTI',
  'SMMF',
  'SMIT',
  'SMDM',
  'SKY',
  'SIMP',
  'SHYF',
  'SHSP',
  'SGMA',
  'SGLB',
  'SGC',
  'SFBC',
  'SESN',
  'SENEA',
  'SEEL',
  'SCYX',
  'SCON',
  'SBFG',
  'SAR',
  'SAL',
  'RSSS',
  'RNWK',
  'RMNI',
  'RM',
  'RILY',
  'RIBT',
  'RHE',
  'RESN',
  'REPH',
  'RELV',
  'REFR',
  'RCKY',
  'RAND',
  'QUIK',
  'QTXB',
  'QTNT',
  'QSEP',
  'QNBC',
  'QCRH',
  'PWOD',
  'PWFL',
  'PURE',
  'PULM',
  'PTMN',
  'PSTV',
  'PSTI',
  'PRTS',
  'PRPO',
  'PRPH',
  'PROV',
  'PRDO',
  'PPSI',
  'PMBC',
  'PLXP',
  'PLX',
  'PLPC',
  'PFMT',
  'PFLT',
  'PEYE',
  'PESI',
  'PEIX',
  'PED',
  'PEBK',
  'PDEX',
  'PCYN',
  'PCTI',
  'PBHC',
  'PAR',
  'OXBR',
  'OVTZ',
  'ORRF',
  'ORN',
  'ORMP',
  'ORGS',
  'ORC',
  'OPTT',
  'OPHC',
  'OPGN',
  'OPCH',
  'ONTX',
  'ONCT',
  'ONCS',
  'OMTK',
  'OFS',
  'OFED',
  'OESX',
  'ODC',
  'OCUP',
  'OBCI',
  'NWIN',
  'NVUS',
  'NURO',
  'NTRP',
  'NTIP',
  'NSYS',
  'NSTG',
  'NSPR',
  'NRIM',
  'NMRD',
  'NLTX',
  'NLST',
  'NIMU',
  'NICK',
  'NERV',
  'NCBS',
  'NBY',
  'NAVB',
  'NATR',
  'NANX',
  'MX',
  'MVIS',
  'MVBF',
  'MTEX',
  'MTEM',
  'MRNS',
  'MRMD',
  'MRCC',
  'MPB',
  'MOSY',
  'MOJO',
  'MNTX',
  'MNOV',
  'MN',
  'MLSS',
  'MITK',
  'MHH',
  'MGEN',
  'MFNC',
  'MEIP',
  'MDVL',
  'MDLY',
  'MCEP',
  'MCCX',
  'MBOT',
  'MATN',
  'MARK',
  'MAGE',
  'LYTS',
  'LWLG',
  'LUVU',
  'LTBR',
  'LSBK',
  'LPTH',
  'LPCN',
  'LODE',
  'LMB',
  'LMAT',
  'LEU',
  'LEDS',
  'LEAT',
  'LEAF',
  'LCUT',
  'LAWS',
  'KTYB',
  'KTCC',
  'KSPN',
  'KOSS',
  'KIN',
  'JUVF',
  'JSDA',
  'JOUT',
  'JCTCF',
  'JCS',
  'JAKK',
  'ITP',
  'ITIC',
  'ITI',
  'ISR',
  'IROQ',
  'IRIX',
  'IPWR',
  'IPDN',
  'INTT',
  'INTI',
  'INTG',
  'INS',
  'INOD',
  'INFU',
  'INBK',
  'IMH',
  'IMBI',
  'III',
  'IESC',
  'IDN',
  'ICCC',
  'ICAD',
  'IAIC',
  'HWBK',
  'HTGM',
  'HSTO',
  'HQI',
  'HPTO',
  'HMNF',
  'HMG',
  'HGBL',
  'HFBL',
  'HEPA',
  'HEAR',
  'HBP',
  'HBNC',
  'GV',
  'GTIM',
  'GROW',
  'GORO',
  'GNSS',
  'GNCA',
  'GLYC',
  'GLGI',
  'GLG',
  'GLBZ',
  'GLAD',
  'GIGA',
  'GHM',
  'GFN',
  'GCBC',
  'GAIA',
  'FVE',
  'FTLF',
  'FTEK',
  'FSBW',
  'FORD',
  'FNWB',
  'FNLC',
  'FMNB',
  'FMBM',
  'FMAO',
  'FLXT',
  'FLXS',
  'FLL',
  'FFWM',
  'FEIM',
  'FDUS',
  'FDBC',
  'FCAP',
  'FBSS',
  'FALC',
  'EYPT',
  'EXEO',
  'EVOL',
  'EVFM',
  'ESXB',
  'ESSA',
  'ESCA',
  'ERII',
  'ENSV',
  'ENG',
  'ENBP',
  'EMYB',
  'EMKR',
  'EMGCQ',
  'EMCF',
  'ELOX',
  'ELMD',
  'EKSO',
  'EGAN',
  'EFSI',
  'ECOM',
  'ECIA',
  'EBTC',
  'EBMT',
  'EARN',
  'DXYN',
  'DWSN',
  'DVD',
  'DSS',
  'DSNY',
  'DRAD',
  'DMRC',
  'DLYT',
  'DLHC',
  'DJCO',
  'DIT',
  'DGLY',
  'DGII',
  'DFFN',
  'DARE',
  'CZWI',
  'CYTR',
  'CYCC',
  'CYBE',
  'CXDO',
  'CWST',
  'CWBC',
  'CVV',
  'CUTR',
  'CTSO',
  'CTIB',
  'CTG',
  'CSBB',
  'CRWS',
  'CRVW',
  'CRMZ',
  'CRMD',
  'CRGS',
  'CREX',
  'CRDF',
  'CRAI',
  'CPTP',
  'CPTA',
  'CPST',
  'CPSH',
  'CPRX',
  'CPIX',
  'CPAH',
  'COMS',
  'COHU',
  'COHN',
  'COFS',
  'CNFN',
  'CNET',
  'CNBKA',
  'CMXC',
  'CMT',
  'CLRO',
  'CLRB',
  'CLIR',
  'CLFD',
  'CLDB',
  'CLCT',
  'CLBS',
  'CKX',
  'CIZN',
  'CIVB',
  'CIO',
  'CHMI',
  'CGIX',
  'CFFI',
  'CFBK',
  'CDZI',
  'CDXC',
  'CDTX',
  'CDNA',
  'CDMO',
  'CCUR',
  'CCEL',
  'CCBG',
  'CBLI',
  'CBKM',
  'CBIO',
  'CBAY',
  'CASH',
  'CARV',
  'CARA',
  'CAPR',
  'CALA',
  'CAC',
  'CAAS',
  'BXC',
  'BWEN',
  'BTN',
  'BSTG',
  'BSRR',
  'BSQR',
  'BRN',
  'BPTH',
  'BLBD',
  'BKTI',
  'BKEP',
  'BIOL',
  'BIOC',
  'BICX',
  'BELFA',
  'BDGE',
  'BCOV',
  'BCLI',
  'BCBP',
  'BBW',
  'BBI',
  'AXR',
  'AXGN',
  'AWX',
  'AWH',
  'AVNW',
  'AUTO',
  'ATRS',
  'ATNM',
  'ATLO',
  'ATLC',
  'ASYS',
  'ASTC',
  'ASPN',
  'ASMB',
  'ARTW',
  'ARDX',
  'APT',
  'APDN',
  'AP',
  'AOSL',
  'ANDR',
  'AMRK',
  'AMRB',
  'AMNB',
  'ALSK',
  'ALDX',
  'AKBA',
  'AIM',
  'AHPI',
  'AHH',
  'AGYS',
  'AEY',
  'AERI',
  'AEHR',
  'AE',
  'ADMT',
  'ADMP',
  'ADMA',
  'ACUR',
  'ACU',
  'ACRX',
  'ACHV',
  'ACFN',
  'ACER',
  'ABMC',
  'ABIO',
  'ABEO',
  'AAME'],
 '2020-06-30': ['ZSAN',
  'ZNOG',
  'ZIVO',
  'YEWB',
  'XTNT',
  'XSPA',
  'XENE',
  'WYY',
  'WWR',
  'WSTL',
  'WSTG',
  'WHLR',
  'WATT',
  'VXRT',
  'VUZI',
  'VNRX',
  'VIVE',
  'VGZ',
  'VERU',
  'VBTX',
  'VBFC',
  'VASO',
  'VALU',
  'VABK',
  'UWHR',
  'UTI',
  'USNU',
  'UNB',
  'UMH',
  'UEC',
  'UCTT',
  'UBOH',
  'UBCP',
  'TSRI',
  'TSBK',
  'TRXC',
  'TRVN',
  'TRUP',
  'TOMZ',
  'TOFB',
  'TNXP',
  'TNLX',
  'TMQ',
  'TIKK',
  'THMO',
  'TGLS',
  'TGHI',
  'TGEN',
  'TENX',
  'TCON',
  'TAYD',
  'SYN',
  'SVT',
  'SUWN',
  'SUNW',
  'SUNS',
  'SUMR',
  'STRS',
  'STRM',
  'STCN',
  'SSY',
  'SSSS',
  'SSNT',
  'SRT',
  'SRNA',
  'SRGZ',
  'SPRT',
  'SPKE',
  'SOTK',
  'SONN',
  'SNSS',
  'SNGX',
  'SNFCA',
  'SNCA',
  'SMTX',
  'SMTI',
  'SMIT',
  'SMED',
  'SKY',
  'SIMP',
  'SHSP',
  'SGLB',
  'SGC',
  'SFBC',
  'SESN',
  'SENEA',
  'SEEL',
  'SCYX',
  'SCON',
  'SCM',
  'SAVA',
  'SAL',
  'RSSS',
  'RSLS',
  'RNWK',
  'RMNI',
  'RILY',
  'RHE',
  'RGCO',
  'RESN',
  'REPH',
  'RELV',
  'REFR',
  'RCKT',
  'RBCN',
  'RAND',
  'QUIK',
  'QTXB',
  'QTNT',
  'QSEP',
  'QNBC',
  'QCRH',
  'PURE',
  'PULM',
  'PTMN',
  'PSTV',
  'PSTI',
  'PRTS',
  'PRPO',
  'PRPH',
  'PROV',
  'PRDO',
  'PLXP',
  'PLX',
  'PLPC',
  'PFLT',
  'PFBI',
  'PESI',
  'PEIX',
  'PDEX',
  'PCYO',
  'PCTI',
  'PBHC',
  'OXBR',
  'OVTZ',
  'ORRF',
  'ORN',
  'ORMP',
  'ORGS',
  'ORC',
  'OPTT',
  'OPOF',
  'OPGN',
  'OPCH',
  'ONTX',
  'ONCT',
  'ONCS',
  'OGEN',
  'OFED',
  'OESX',
  'ODC',
  'OCUP',
  'OBCI',
  'NWIN',
  'NVUS',
  'NVOS',
  'NUVR',
  'NTRP',
  'NSTG',
  'NSPR',
  'NRIM',
  'NMRD',
  'NLST',
  'NIMU',
  'NICK',
  'NERV',
  'NCBS',
  'NAVB',
  'NATR',
  'NANX',
  'MX',
  'MVIS',
  'MVBF',
  'MTEX',
  'MTEM',
  'MRNS',
  'MRCC',
  'MPB',
  'MOSY',
  'MOJO',
  'MNOV',
  'MN',
  'MITK',
  'MHH',
  'MGEN',
  'MFNC',
  'MEIP',
  'MDVL',
  'MCEP',
  'MCBC',
  'MBOT',
  'MATN',
  'LYTS',
  'LWLG',
  'LUVU',
  'LTBR',
  'LSBK',
  'LPTH',
  'LPCN',
  'LODE',
  'LMB',
  'LEU',
  'LEDS',
  'LEAT',
  'LEAF',
  'LCNB',
  'LAWS',
  'KTCC',
  'KSPN',
  'KINS',
  'KIN',
  'JSDA',
  'JOUT',
  'JCTCF',
  'JCS',
  'ITP',
  'ITIC',
  'ITI',
  'ISR',
  'IROQ',
  'IRIX',
  'IPWR',
  'IPDN',
  'INTI',
  'INS',
  'INFU',
  'IMH',
  'IMBI',
  'IESC',
  'IDN',
  'ICCC',
  'IAIC',
  'HTGM',
  'HSTO',
  'HSON',
  'HRZN',
  'HPTO',
  'HMNF',
  'HMG',
  'HGBL',
  'HEPA',
  'HBP',
  'GV',
  'GROW',
  'GNSS',
  'GNCA',
  'GLGI',
  'GLAD',
  'GIGA',
  'GFN',
  'GFED',
  'GEC',
  'GCBC',
  'GALT',
  'GAIA',
  'FVE',
  'FSBW',
  'FRAF',
  'FNWB',
  'FNLC',
  'FMNB',
  'FMBM',
  'FMAO',
  'FLXT',
  'FFWM',
  'FCAP',
  'FBSS',
  'FBIO',
  'FALC',
  'EYPT',
  'EXEO',
  'EVOL',
  'EVFM',
  'ESXB',
  'ESSA',
  'ESP',
  'ESCA',
  'ERII',
  'EQUR',
  'ENG',
  'ENBP',
  'EMYB',
  'EMKR',
  'EMGCQ',
  'ELOX',
  'ELMD',
  'EKSO',
  'EHTH',
  'EGAN',
  'EFSI',
  'ECOM',
  'EBMT',
  'EARN',
  'DXYN',
  'DWSN',
  'DSNY',
  'DMRC',
  'DLYT',
  'DLHC',
  'DJCO',
  'DIT',
  'DGLY',
  'DFFN',
  'DENR',
  'DARE',
  'CZWI',
  'CYTR',
  'CYCC',
  'CYBE',
  'CXDO',
  'CWST',
  'CVV',
  'CTSO',
  'CTG',
  'CSBB',
  'CRWS',
  'CRVW',
  'CRMZ',
  'CRMD',
  'CRK',
  'CRGS',
  'CREX',
  'CRDF',
  'CRAI',
  'CPTP',
  'CPST',
  'CPSH',
  'CPRX',
  'CPIX',
  'CPAH',
  'COMS',
  'COHU',
  'COHN',
  'COFS',
  'CNFN',
  'CNET',
  'CNBKA',
  'CMXC',
  'CMT',
  'CLSN',
  'CLRO',
  'CLRB',
  'CLIR',
  'CLFD',
  'CLCT',
  'CLBS',
  'CKX',
  'CJJD',
  'CIVB',
  'CIO',
  'CIIT',
  'CIA',
  'CHMG',
  'CGIX',
  'CFBK',
  'CEI',
  'CDZI',
  'CDXC',
  'CDTX',
  'CDNA',
  'CDMO',
  'CCUR',
  'CCEL',
  'CCBG',
  'CBLI',
  'CBFV',
  'CBAY',
  'CASH',
  'CARV',
  'CAPR',
  'CALA',
  'BXC',
  'BWEN',
  'BTN',
  'BSTG',
  'BSRR',
  'BSQR',
  'BRG',
  'BPTH',
  'BKEP',
  'BIOL',
  'BIOC',
  'BICX',
  'BDGE',
  'BCOV',
  'BBI',
  'AWH',
  'AUTO',
  'ATRS',
  'ATNM',
  'ATLO',
  'ATLC',
  'ASUR',
  'ASTC',
  'ASPU',
  'ASPN',
  'ASMB',
  'ARTW',
  'ARDX',
  'APT',
  'APEX',
  'APDN',
  'AP',
  'ANFC',
  'ANDR',
  'AMTX',
  'AMSWA',
  'AMRK',
  'AMRB',
  'ALT',
  'ALSK',
  'ALDX',
  'AIM',
  'AHH',
  'AGRX',
  'AERI',
  'ADMT',
  'ADMP',
  'ADMA',
  'ACUR',
  'ACU',
  'ACRX',
  'ACHV',
  'ACFN',
  'ACER',
  'ABMC',
  'ABIO',
  'ABEO',
  'AAME'],
 '2020-03-31': ['WYY',
  'WATT',
  'VIVE',
  'UTI',
  'TOMZ',
  'TNXP',
  'TMQ',
  'TIKK',
  'TGHI',
  'TCON',
  'SOTK',
  'SNSS',
  'SHSP',
  'SAR',
  'SAMG',
  'RESN',
  'REI',
  'QTNT',
  'PURE',
  'PLX',
  'PFBX',
  'ORGS',
  'OPGN',
  'OPCH',
  'ONCS',
  'NLST',
  'MTEX',
  'LEDS',
  'LAWS',
  'ITI',
  'IRIX',
  'IPWR',
  'IDN',
  'GLYC',
  'GLGI',
  'FTLF',
  'EVOK',
  'ESSA',
  'EBMT',
  'CYCC',
  'CVCY',
  'CPAH',
  'CLIR',
  'CDXC',
  'CASH',
  'CAPR',
  'BIOC',
  'BBQ',
  'ASPU',
  'ARDX',
  'APT',
  'APDN',
  'AMRK',
  'ABIO'],
 '2019-12-31': ['ZIVO',
  'XSPA',
  'WYY',
  'WATT',
  'VNRX',
  'VIVE',
  'VASO',
  'UTI',
  'UFPT',
  'UBOH',
  'TSBK',
  'TNXP',
  'TKOI',
  'TIKK',
  'TCON',
  'TCFC',
  'TAYD',
  'SWKH',
  'STKS',
  'SOTK',
  'SNSS',
  'SNCA',
  'SMIT',
  'SGLB',
  'SFST',
  'SENEA',
  'SEEL',
  'SCON',
  'SAR',
  'SAL',
  'RM',
  'QTNT',
  'QCRH',
  'PULM',
  'PSTV',
  'PLX',
  'PDEX',
  'PCYO',
  'PAYS',
  'ORC',
  'OPGN',
  'ONTX',
  'ONCT',
  'OEG',
  'NSTG',
  'NMRD',
  'NLST',
  'NKSH',
  'NAVB',
  'MTEX',
  'MMAC',
  'MLR',
  'MCBC',
  'LSBK',
  'LODE',
  'KTYB',
  'JCS',
  'ISR',
  'IRT',
  'IRMD',
  'IRIX',
  'IPWR',
  'INS',
  'IDN',
  'HRZN',
  'GLXZ',
  'GFN',
  'GCBC',
  'FNWB',
  'FNLC',
  'FMNB',
  'FBIZ',
  'EVTN',
  'ENG',
  'ELMD',
  'EKSO',
  'EHTH',
  'EGAN',
  'EFSI',
  'ECOM',
  'DXYN',
  'DSNY',
  'CXDO',
  'CWBC',
  'CSBB',
  'CRWS',
  'CRK',
  'CPRX',
  'CPAH',
  'CLRB',
  'CLIR',
  'CGIX',
  'CFBK',
  'CCNE',
  'CCBG',
  'CBFV',
  'BSTG',
  'BSTC',
  'BSRR',
  'BPTH',
  'BIOL',
  'BIOC',
  'AUBN',
  'ATRS',
  'ATNM',
  'ASUR',
  'APDN',
  'AIM',
  'AGRX',
  'ADMP',
  'ADMA',
  'ACFN',
  'ABIO'],
 '2019-09-30': ['WVFC',
  'WATT',
  'VUZI',
  'VNRX',
  'VIVE',
  'VCYT',
  'UNAM',
  'UFPT',
  'UBFO',
  'TSBK',
  'TNXP',
  'TAT',
  'STRM',
  'SSNT',
  'SRNA',
  'SNSS',
  'SNMP',
  'SGLB',
  'SFST',
  'SEEL',
  'SCON',
  'SAL',
  'RM',
  'RILY',
  'RHE',
  'RCKY',
  'QCRH',
  'PURE',
  'PULM',
  'PSTV',
  'PPSI',
  'PLX',
  'PFBI',
  'PCYO',
  'PAYS',
  'ONCT',
  'ONCS',
  'OESX',
  'NLST',
  'NKSH',
  'MTEM',
  'MIND',
  'MGYR',
  'MCEP',
  'MCBC',
  'LODE',
  'LIQT',
  'LGL',
  'LEAT',
  'KTYB',
  'JCS',
  'ISTR',
  'ISR',
  'ISNS',
  'IRMD',
  'IRIX',
  'IPWR',
  'INTZ',
  'INS',
  'ICBK',
  'HRZN',
  'HBNC',
  'GLXZ',
  'GEOS',
  'GCBC',
  'FNLC',
  'FMNB',
  'FDBC',
  'FCAP',
  'EMGCQ',
  'EKSO',
  'ECOM',
  'EBMT',
  'CYTR',
  'CXDO',
  'CSBB',
  'CRVW',
  'CPRX',
  'CLRB',
  'CLIR',
  'CFBK',
  'CDTX',
  'CCNE',
  'CBLI',
  'CBFV',
  'BSTC',
  'BSRR',
  'BRG',
  'BPTH',
  'BLFS',
  'BIOC',
  'APDN',
  'AIRT',
  'AGRX',
  'ADMP',
  'ADMA',
  'ACRX',
  'ABIO'],
 '2019-06-30': ['WATT',
  'VIVE',
  'VCYT',
  'UFPT',
  'UBFO',
  'TSBK',
  'TRVN',
  'TPVG',
  'TNXP',
  'SRNA',
  'SFST',
  'SEEL',
  'SCON',
  'SAL',
  'QTNT',
  'PURE',
  'PULM',
  'PTN',
  'PFIN',
  'PAYS',
  'ONCS',
  'OESX',
  'NLST',
  'NCBS',
  'MVBF',
  'MLR',
  'MHH',
  'MCEP',
  'MCBC',
  'LIQT',
  'LGL',
  'KVHI',
  'JCS',
  'ISTR',
  'IRMD',
  'INTZ',
  'HSTO',
  'GLXZ',
  'GIGA',
  'FNLC',
  'FMAO',
  'FDBC',
  'FCAP',
  'FBIZ',
  'EKSO',
  'DGLY',
  'CXDO',
  'CSBB',
  'CPRX',
  'CNFN',
  'CLRB',
  'CFBK',
  'BSTC',
  'BSRR',
  'BPTH',
  'BOOM',
  'BIOC',
  'ATNM',
  'APDN',
  'AJX',
  'AGRX',
  'ACRX',
  'ACNB',
  'ABIO'],
 '2019-03-31': ['ZSAN',
  'WVFC',
  'WATT',
  'VPG',
  'VIVE',
  'VCYT',
  'UBFO',
  'TSBK',
  'TRVN',
  'TRNS',
  'TNXP',
  'THM',
  'SVBI',
  'SSY',
  'SNSS',
  'SNGX',
  'SESN',
  'SCON',
  'SAVA',
  'RCMT',
  'RC',
  'QTNT',
  'PULM',
  'PSTV',
  'PFBI',
  'PAYS',
  'ORGS',
  'OPTT',
  'ONCS',
  'OESX',
  'NSEC',
  'NMRD',
  'NLST',
  'NKSH',
  'NEON',
  'NCBS',
  'MGYR',
  'MCBC',
  'MATN',
  'LTRX',
  'LODE',
  'LIQT',
  'LGL',
  'JMP',
  'JCS',
  'ISTR',
  'IRMD',
  'IPWR',
  'INTZ',
  'INS',
  'ICD',
  'HUSA',
  'HALL',
  'GEOS',
  'GCBC',
  'FNLC',
  'FMNB',
  'FDBC',
  'FBIZ',
  'FBIO',
  'ENZ',
  'ENSV',
  'EGAN',
  'EBTC',
  'DIT',
  'CXDO',
  'CWCO',
  'CTEK',
  'CSBB',
  'CRVW',
  'CRDF',
  'CLRB',
  'CLIR',
  'CFBK',
  'BSRR',
  'BOOM',
  'BIOC',
  'BDR',
  'AUBN',
  'AGTC',
  'AGRX',
  'ACRX',
  'ACNB',
  'ABIO'],
 '2018-12-31': ['ZSAN',
  'ZAGG',
  'XONE',
  'WVFC',
  'WATT',
  'VIVE',
  'VCYT',
  'VCEL',
  'UPLD',
  'UONE',
  'ULBI',
  'UFPT',
  'UEC',
  'UBOH',
  'UBFO',
  'TSBK',
  'TRVN',
  'THM',
  'TESS',
  'TCI',
  'SVT',
  'SVBI',
  'SPRS',
  'SNSS',
  'SNCA',
  'SESN',
  'SCON',
  'SAVA',
  'SAL',
  'RVSB',
  'RM',
  'RAND',
  'QUIK',
  'QNST',
  'QMCI',
  'QCRH',
  'PSTV',
  'PFSW',
  'PFBI',
  'PBHC',
  'PAYS',
  'OXFD',
  'OPGN',
  'ONCT',
  'ONCS',
  'OGEN',
  'OFLX',
  'OCFC',
  'NTWK',
  'NOVC',
  'NLST',
  'NKSH',
  'NCBS',
  'NATH',
  'MMAC',
  'MLR',
  'MGYR',
  'MDVL',
  'MCBC',
  'MBCN',
  'MATN',
  'LODE',
  'LLEXQ',
  'LEAF',
  'JCAP',
  'IVAC',
  'IPWR',
  'INTZ',
  'INS',
  'HTGM',
  'HROW',
  'HOFT',
  'HBNC',
  'HBIO',
  'GSIT',
  'GNCA',
  'GCBC',
  'FZMD',
  'FTEK',
  'FSBW',
  'FNLC',
  'FMNB',
  'FIVN',
  'FDBC',
  'FCAP',
  'ENZN',
  'EML',
  'EKSO',
  'EGAN',
  'CTHR',
  'CSBB',
  'CRMD',
  'CRK',
  'CRDF',
  'CPHC',
  'CLSN',
  'CLRB',
  'CLIR',
  'CFBK',
  'CDTX',
  'CCBG',
  'CBKM',
  'BSTG',
  'BSTC',
  'BOTJ',
  'BOOM',
  'BLFS',
  'BKSC',
  'BFIN',
  'AWH',
  'AVEO',
  'AUBN',
  'ATRS',
  'ATNM',
  'ATLC',
  'ARL',
  'AMSC',
  'ALOT',
  'AIKI',
  'AGRX',
  'ABIO'],
 '2018-09-30': ['ZSAN',
  'ZAGG',
  'XXII',
  'WVFC',
  'WHF',
  'VPG',
  'UG',
  'UFPT',
  'UEC',
  'UBFO',
  'UBCP',
  'UAMY',
  'TRVN',
  'TRUP',
  'TCI',
  'SYNL',
  'SVT',
  'SLNG',
  'SIGA',
  'SAVA',
  'RYI',
  'RVSB',
  'RLH',
  'RCKY',
  'RCKT',
  'QUIK',
  'PSTV',
  'PFBI',
  'PCYO',
  'OPGN',
  'ONCS',
  'OFLX',
  'NWPX',
  'NTN',
  'NTIC',
  'NCBS',
  'MVIS',
  'MGYR',
  'MBCN',
  'MATN',
  'LOAN',
  'LMRK',
  'LEAT',
  'LAND',
  'ISTR',
  'IOR',
  'INSG',
  'INS',
  'INOD',
  'IIN',
  'IEC',
  'HWCC',
  'HCHC',
  'GNCA',
  'GEOS',
  'GCBC',
  'GALT',
  'GAIN',
  'FXNC',
  'FNLC',
  'FMNB',
  'FMAO',
  'FDBC',
  'FCAP',
  'FBIZ',
  'EGY',
  'EGAN',
  'CWCO',
  'CSBB',
  'CRVW',
  'CRK',
  'CRDF',
  'CLIR',
  'CBKM',
  'CBAT',
  'BSTG',
  'BSTC',
  'BLPH',
  'BLFS',
  'BBI',
  'ATRS',
  'ARL',
  'APYX',
  'APT',
  'AMSC',
  'ALIM',
  'AGRX',
  'ACNB',
  'ABIO'],
 '2018-06-30': ['ZSAN',
  'ZEUS',
  'WVFC',
  'WHF',
  'VTNR',
  'VPG',
  'VIVE',
  'UG',
  'UBFO',
  'UBCP',
  'TWIN',
  'TSBK',
  'SYNL',
  'STRT',
  'SNSS',
  'SNCA',
  'SMIT',
  'SFBC',
  'RVSB',
  'RSRV',
  'RCKT',
  'QNST',
  'PSTV',
  'PRSI',
  'PFIE',
  'PED',
  'PCYO',
  'PAYS',
  'OPHC',
  'OPGN',
  'OMEX',
  'NLTX',
  'NCBS',
  'MSB',
  'MPX',
  'MICT',
  'MHH',
  'MGYR',
  'MCCX',
  'MATN',
  'LTRX',
  'LMAT',
  'ISTR',
  'IPWR',
  'INTG',
  'IIN',
  'HWCC',
  'HTGM',
  'HROW',
  'HGBL',
  'HBNC',
  'GNCA',
  'GLG',
  'GCBC',
  'FRD',
  'FNLC',
  'FMNB',
  'FMAO',
  'FDBC',
  'ESCA',
  'ERII',
  'EFSI',
  'DSS',
  'CXDO',
  'CVLY',
  'CSBB',
  'CRDF',
  'COHU',
  'CLRB',
  'CLDB',
  'CIX',
  'CBIO',
  'BSTG',
  'BSTC',
  'BSRR',
  'BLFS',
  'BFIN',
  'ATNM',
  'ATHX',
  'ACNB',
  'ABIO'],
 '2018-03-31': ['XXII',
  'WVFC',
  'WHF',
  'VXRT',
  'VPG',
  'VABK',
  'UNB',
  'UCTT',
  'UBFO',
  'UBCP',
  'TSBK',
  'TRNS',
  'TIPT',
  'TGC',
  'SYNL',
  'SNSS',
  'SNFCA',
  'SNCA',
  'RCKY',
  'RCKT',
  'QNST',
  'QCRH',
  'PSTV',
  'PSTI',
  'PLXP',
  'PLBC',
  'PFIE',
  'PFBI',
  'PCYO',
  'OPGN',
  'ONCS',
  'NCBS',
  'MXC',
  'MTEM',
  'MRNS',
  'MPX',
  'MATN',
  'KTYB',
  'IPWR',
  'HWCC',
  'HTGM',
  'HSON',
  'HMG',
  'HGBL',
  'HBNC',
  'GCBC',
  'FXNC',
  'FRD',
  'FORD',
  'FNLC',
  'FMNB',
  'FMAO',
  'FFNW',
  'FDBC',
  'ENSV',
  'EFSI',
  'CXDO',
  'CSBB',
  'CRDF',
  'CPST',
  'CLSN',
  'CKX',
  'CIO',
  'CDMO',
  'CBIO',
  'CARV',
  'BSTG',
  'BSTC',
  'BLPH',
  'APDN',
  'ACNB',
  'ACER',
  'ABIO'],
 '2017-12-31': ['ZSAN',
  'WVVI',
  'WSTL',
  'WLFC',
  'VEC',
  'VCEL',
  'VALU',
  'USAP',
  'USAK',
  'UONE',
  'ULBI',
  'UCTT',
  'TNXP',
  'TACO',
  'SUWN',
  'STRM',
  'STCN',
  'SPRT',
  'SNSS',
  'SNFCA',
  'SNCA',
  'SMIT',
  'SLNG',
  'SCON',
  'SBFG',
  'RNWK',
  'RM',
  'RLGT',
  'RELL',
  'REEMF',
  'RCKY',
  'QUIK',
  'QTXB',
  'QNST',
  'PLXP',
  'PFSW',
  'PFIE',
  'PCYO',
  'PATI',
  'OTEL',
  'OPGN',
  'NVUS',
  'NVEE',
  'NUVR',
  'NERV',
  'NCBS',
  'MRNS',
  'MLR',
  'MCCX',
  'MATN',
  'LMST',
  'LMAT',
  'LEU',
  'LEE',
  'LCNB',
  'LAWS',
  'ITIC',
  'IPWR',
  'INTZ',
  'IMBI',
  'HWCC',
  'HTGM',
  'HSTO',
  'HPTO',
  'HNNA',
  'HEAR',
  'GVP',
  'GLYC',
  'GFN',
  'GCBC',
  'GALT',
  'FZMD',
  'FVE',
  'FRBK',
  'FNLC',
  'FMAO',
  'FLXT',
  'FDBC',
  'FALC',
  'EVOK',
  'ESP',
  'ESCA',
  'ERII',
  'EKSO',
  'DJCO',
  'DAIO',
  'CYTR',
  'CYCC',
  'CXDO',
  'CWGL',
  'CVV',
  'CUTR',
  'CTHR',
  'CSBR',
  'CRDF',
  'CPST',
  'CLSN',
  'CKX',
  'CIX',
  'CBAY',
  'CAPR',
  'BXC',
  'BSTG',
  'BCLI',
  'BBGI',
  'AVNW',
  'ATNM',
  'ASYS',
  'ASMB',
  'ARDX',
  'AOSL',
  'AKBA',
  'ACY',
  'ACHV',
  'ACER',
  'AAME'],
 '2017-09-30': ['ZSAN',
  'WVFC',
  'VOXX',
  'UBFO',
  'UBCP',
  'TWIN',
  'TRUP',
  'TCON',
  'TCFC',
  'SPRT',
  'SNCA',
  'SHYF',
  'SGA',
  'SFST',
  'RVSB',
  'QUIK',
  'QNST',
  'PTN',
  'PLXP',
  'PLPC',
  'PLBC',
  'PEYE',
  'OPGN',
  'OBLG',
  'NVUS',
  'NVEE',
  'NUVR',
  'NTN',
  'NCBS',
  'MSB',
  'MRNS',
  'MITK',
  'MGYR',
  'LUNA',
  'LOAN',
  'LMAT',
  'IPWR',
  'INTZ',
  'INTT',
  'INBK',
  'HTBK',
  'HSTO',
  'HPTO',
  'GROW',
  'GLYC',
  'GFED',
  'GCBC',
  'FNRN',
  'FLXT',
  'FIVN',
  'FDBC',
  'FALC',
  'EVBN',
  'EMYB',
  'DMRC',
  'DARE',
  'DAIO',
  'CXDO',
  'CUTR',
  'CTHR',
  'CSBR',
  'CNTY',
  'CNBKA',
  'CLSN',
  'CLDB',
  'CHMG',
  'CCBG',
  'CBAN',
  'CALA',
  'BWFG',
  'BSTG',
  'BFIN',
  'AXTI',
  'ASYS',
  'ASTC',
  'ARDX',
  'APT',
  'AOSL',
  'ACER'],
 '2017-06-30': ['ZSAN',
  'YEWB',
  'VABK',
  'UCTT',
  'UBFO',
  'TSBK',
  'TRUP',
  'TNXP',
  'TCFC',
  'TBK',
  'SNCA',
  'SMGI',
  'SCYX',
  'SCON',
  'RVSB',
  'REEMF',
  'QUIK',
  'PTN',
  'PRTS',
  'PLXP',
  'PLBC',
  'PFIE',
  'PAR',
  'NWIN',
  'NUVR',
  'NSPR',
  'MSB',
  'MRNS',
  'MPX',
  'MPB',
  'MCCX',
  'MCBC',
  'LPTH',
  'LMAT',
  'JCTCF',
  'IPWR',
  'HROW',
  'HPTO',
  'GLGI',
  'GCBC',
  'FSBW',
  'FNRN',
  'FMAO',
  'FLXT',
  'FDBC',
  'FCAP',
  'EVTN',
  'EVOK',
  'ECIA',
  'DARE',
  'DAIO',
  'CYCC',
  'CXDO',
  'CSBR',
  'CPST',
  'COHU',
  'CNBKA',
  'CMXC',
  'CLSN',
  'CLBS',
  'CDMO',
  'CCUR',
  'CBAN',
  'CALA',
  'BWFG',
  'BRG',
  'BLPH',
  'AWH',
  'AOSL',
  'ACER']}

In [49]:
names = ['TCON','TMBR', 'TAT', 'BSTC','ZSAN','RCKT','TAT','LLEXQ','WSTL','NTRP','JCAP','RKDA','RMNI','PATI', 'ZEUS']

quarter = []
comp =[]
position =[]
bp=[]
sp=[]
pnl =[]
end=[]
i=0
j=0

In [50]:
long_port

{'2020-09-30': ['ZSAN',
  'ZNOG',
  'ZIVO',
  'ZGNX',
  'YEWB',
  'XTNT',
  'XSPA',
  'XENE',
  'WYY',
  'WWR',
  'WVVI',
  'WSTL',
  'WHLR',
  'WHF',
  'WATT',
  'VXRT',
  'VUZI',
  'VOXX',
  'VNRX',
  'VIVE',
  'VIRC',
  'VGZ',
  'VCRA',
  'VCEL',
  'VBTX',
  'VBFC',
  'VASO',
  'VALU',
  'UWHR',
  'UUU',
  'UTI',
  'USNU',
  'USIO',
  'URG',
  'UNB',
  'UMH',
  'UCTT',
  'UBOH',
  'UBCP',
  'TSRI',
  'TSBK',
  'TRXC',
  'TRVN',
  'TOMZ',
  'TOFB',
  'TNXP',
  'TNLX',
  'TMQ',
  'TIPT',
  'TIKK',
  'THMO',
  'TGLS',
  'TGHI',
  'TGEN',
  'TENX',
  'TCON',
  'TBK',
  'SYN',
  'SWKH',
  'SUWN',
  'SUNW',
  'SUNS',
  'SUMR',
  'STRT',
  'STRM',
  'STCN',
  'SSSS',
  'SRT',
  'SRNA',
  'SRGZ',
  'SPRT',
  'SPND',
  'SPKE',
  'SOTK',
  'SONN',
  'SNSS',
  'SNGX',
  'SNFCA',
  'SNCA',
  'SMTX',
  'SMTI',
  'SMMF',
  'SMIT',
  'SMDM',
  'SKY',
  'SIMP',
  'SHYF',
  'SHSP',
  'SGMA',
  'SGLB',
  'SGC',
  'SFBC',
  'SESN',
  'SENEA',
  'SEEL',
  'SCYX',
  'SCON',
  'SBFG',
  'SAR',
  'SAL',
  'RSSS',
  'RNWK',
  'RMNI',
  'RM',
  'RILY',
  'RIBT',
  'RHE',
  'RESN',
  'REPH',
  'RELV',
  'REFR',
  'RCKY',
  'RAND',
  'QUIK',
  'QTXB',
  'QTNT',
  'QSEP',
  'QNBC',
  'QCRH',
  'PWOD',
  'PWFL',
  'PURE',
  'PULM',
  'PTMN',
  'PSTV',
  'PSTI',
  'PRTS',
  'PRPO',
  'PRPH',
  'PROV',
  'PRDO',
  'PPSI',
  'PMBC',
  'PLXP',
  'PLX',
  'PLPC',
  'PFMT',
  'PFLT',
  'PEYE',
  'PESI',
  'PEIX',
  'PED',
  'PEBK',
  'PDEX',
  'PCYN',
  'PCTI',
  'PBHC',
  'PAR',
  'OXBR',
  'OVTZ',
  'ORRF',
  'ORN',
  'ORMP',
  'ORGS',
  'ORC',
  'OPTT',
  'OPHC',
  'OPGN',
  'OPCH',
  'ONTX',
  'ONCT',
  'ONCS',
  'OMTK',
  'OFS',
  'OFED',
  'OESX',
  'ODC',
  'OCUP',
  'OBCI',
  'NWIN',
  'NVUS',
  'NURO',
  'NTRP',
  'NTIP',
  'NSYS',
  'NSTG',
  'NSPR',
  'NRIM',
  'NMRD',
  'NLTX',
  'NLST',
  'NIMU',
  'NICK',
  'NERV',
  'NCBS',
  'NBY',
  'NAVB',
  'NATR',
  'NANX',
  'MX',
  'MVIS',
  'MVBF',
  'MTEX',
  'MTEM',
  'MRNS',
  'MRMD',
  'MRCC',
  'MPB',
  'MOSY',
  'MOJO',
  'MNTX',
  'MNOV',
  'MN',
  'MLSS',
  'MITK',
  'MHH',
  'MGEN',
  'MFNC',
  'MEIP',
  'MDVL',
  'MDLY',
  'MCEP',
  'MCCX',
  'MBOT',
  'MATN',
  'MARK',
  'MAGE',
  'LYTS',
  'LWLG',
  'LUVU',
  'LTBR',
  'LSBK',
  'LPTH',
  'LPCN',
  'LODE',
  'LMB',
  'LMAT',
  'LEU',
  'LEDS',
  'LEAT',
  'LEAF',
  'LCUT',
  'LAWS',
  'KTYB',
  'KTCC',
  'KSPN',
  'KOSS',
  'KIN',
  'JUVF',
  'JSDA',
  'JOUT',
  'JCTCF',
  'JCS',
  'JAKK',
  'ITP',
  'ITIC',
  'ITI',
  'ISR',
  'IROQ',
  'IRIX',
  'IPWR',
  'IPDN',
  'INTT',
  'INTI',
  'INTG',
  'INS',
  'INOD',
  'INFU',
  'INBK',
  'IMH',
  'IMBI',
  'III',
  'IESC',
  'IDN',
  'ICCC',
  'ICAD',
  'IAIC',
  'HWBK',
  'HTGM',
  'HSTO',
  'HQI',
  'HPTO',
  'HMNF',
  'HMG',
  'HGBL',
  'HFBL',
  'HEPA',
  'HEAR',
  'HBP',
  'HBNC',
  'GV',
  'GTIM',
  'GROW',
  'GORO',
  'GNSS',
  'GNCA',
  'GLYC',
  'GLGI',
  'GLG',
  'GLBZ',
  'GLAD',
  'GIGA',
  'GHM',
  'GFN',
  'GCBC',
  'GAIA',
  'FVE',
  'FTLF',
  'FTEK',
  'FSBW',
  'FORD',
  'FNWB',
  'FNLC',
  'FMNB',
  'FMBM',
  'FMAO',
  'FLXT',
  'FLXS',
  'FLL',
  'FFWM',
  'FEIM',
  'FDUS',
  'FDBC',
  'FCAP',
  'FBSS',
  'FALC',
  'EYPT',
  'EXEO',
  'EVOL',
  'EVFM',
  'ESXB',
  'ESSA',
  'ESCA',
  'ERII',
  'ENSV',
  'ENG',
  'ENBP',
  'EMYB',
  'EMKR',
  'EMGCQ',
  'EMCF',
  'ELOX',
  'ELMD',
  'EKSO',
  'EGAN',
  'EFSI',
  'ECOM',
  'ECIA',
  'EBTC',
  'EBMT',
  'EARN',
  'DXYN',
  'DWSN',
  'DVD',
  'DSS',
  'DSNY',
  'DRAD',
  'DMRC',
  'DLYT',
  'DLHC',
  'DJCO',
  'DIT',
  'DGLY',
  'DGII',
  'DFFN',
  'DARE',
  'CZWI',
  'CYTR',
  'CYCC',
  'CYBE',
  'CXDO',
  'CWST',
  'CWBC',
  'CVV',
  'CUTR',
  'CTSO',
  'CTIB',
  'CTG',
  'CSBB',
  'CRWS',
  'CRVW',
  'CRMZ',
  'CRMD',
  'CRGS',
  'CREX',
  'CRDF',
  'CRAI',
  'CPTP',
  'CPTA',
  'CPST',
  'CPSH',
  'CPRX',
  'CPIX',
  'CPAH',
  'COMS',
  'COHU',
  'COHN',
  'COFS',
  'CNFN',
  'CNET',
  'CNBKA',
  'CMXC',
  'CMT',
  'CLRO',
  'CLRB',
  'CLIR',
  'CLFD',
  'CLDB',
  'CLCT',
  'CLBS',
  'CKX',
  'CIZN',
  'CIVB',
  'CIO',
  'CHMI',
  'CGIX',
  'CFFI',
  'CFBK',
  'CDZI',
  'CDXC',
  'CDTX',
  'CDNA',
  'CDMO',
  'CCUR',
  'CCEL',
  'CCBG',
  'CBLI',
  'CBKM',
  'CBIO',
  'CBAY',
  'CASH',
  'CARV',
  'CARA',
  'CAPR',
  'CALA',
  'CAC',
  'CAAS',
  'BXC',
  'BWEN',
  'BTN',
  'BSTG',
  'BSRR',
  'BSQR',
  'BRN',
  'BPTH',
  'BLBD',
  'BKTI',
  'BKEP',
  'BIOL',
  'BIOC',
  'BICX',
  'BELFA',
  'BDGE',
  'BCOV',
  'BCLI',
  'BCBP',
  'BBW',
  'BBI',
  'AXR',
  'AXGN',
  'AWX',
  'AWH',
  'AVNW',
  'AUTO',
  'ATRS',
  'ATNM',
  'ATLO',
  'ATLC',
  'ASYS',
  'ASTC',
  'ASPN',
  'ASMB',
  'ARTW',
  'ARDX',
  'APT',
  'APDN',
  'AP',
  'AOSL',
  'ANDR',
  'AMRK',
  'AMRB',
  'AMNB',
  'ALSK',
  'ALDX',
  'AKBA',
  'AIM',
  'AHPI',
  'AHH',
  'AGYS',
  'AEY',
  'AERI',
  'AEHR',
  'AE',
  'ADMT',
  'ADMP',
  'ADMA',
  'ACUR',
  'ACU',
  'ACRX',
  'ACHV',
  'ACFN',
  'ACER',
  'ABMC',
  'ABIO',
  'ABEO',
  'AAME'],
 '2020-06-30': ['ZSAN',
  'ZNOG',
  'ZIVO',
  'YEWB',
  'XTNT',
  'XSPA',
  'XENE',
  'WYY',
  'WWR',
  'WSTL',
  'WSTG',
  'WHLR',
  'WATT',
  'VXRT',
  'VUZI',
  'VNRX',
  'VIVE',
  'VGZ',
  'VERU',
  'VBTX',
  'VBFC',
  'VASO',
  'VALU',
  'VABK',
  'UWHR',
  'UTI',
  'USNU',
  'UNB',
  'UMH',
  'UEC',
  'UCTT',
  'UBOH',
  'UBCP',
  'TSRI',
  'TSBK',
  'TRXC',
  'TRVN',
  'TRUP',
  'TOMZ',
  'TOFB',
  'TNXP',
  'TNLX',
  'TMQ',
  'TIKK',
  'THMO',
  'TGLS',
  'TGHI',
  'TGEN',
  'TENX',
  'TCON',
  'TAYD',
  'SYN',
  'SVT',
  'SUWN',
  'SUNW',
  'SUNS',
  'SUMR',
  'STRS',
  'STRM',
  'STCN',
  'SSY',
  'SSSS',
  'SSNT',
  'SRT',
  'SRNA',
  'SRGZ',
  'SPRT',
  'SPKE',
  'SOTK',
  'SONN',
  'SNSS',
  'SNGX',
  'SNFCA',
  'SNCA',
  'SMTX',
  'SMTI',
  'SMIT',
  'SMED',
  'SKY',
  'SIMP',
  'SHSP',
  'SGLB',
  'SGC',
  'SFBC',
  'SESN',
  'SENEA',
  'SEEL',
  'SCYX',
  'SCON',
  'SCM',
  'SAVA',
  'SAL',
  'RSSS',
  'RSLS',
  'RNWK',
  'RMNI',
  'RILY',
  'RHE',
  'RGCO',
  'RESN',
  'REPH',
  'RELV',
  'REFR',
  'RCKT',
  'RBCN',
  'RAND',
  'QUIK',
  'QTXB',
  'QTNT',
  'QSEP',
  'QNBC',
  'QCRH',
  'PURE',
  'PULM',
  'PTMN',
  'PSTV',
  'PSTI',
  'PRTS',
  'PRPO',
  'PRPH',
  'PROV',
  'PRDO',
  'PLXP',
  'PLX',
  'PLPC',
  'PFLT',
  'PFBI',
  'PESI',
  'PEIX',
  'PDEX',
  'PCYO',
  'PCTI',
  'PBHC',
  'OXBR',
  'OVTZ',
  'ORRF',
  'ORN',
  'ORMP',
  'ORGS',
  'ORC',
  'OPTT',
  'OPOF',
  'OPGN',
  'OPCH',
  'ONTX',
  'ONCT',
  'ONCS',
  'OGEN',
  'OFED',
  'OESX',
  'ODC',
  'OCUP',
  'OBCI',
  'NWIN',
  'NVUS',
  'NVOS',
  'NUVR',
  'NTRP',
  'NSTG',
  'NSPR',
  'NRIM',
  'NMRD',
  'NLST',
  'NIMU',
  'NICK',
  'NERV',
  'NCBS',
  'NAVB',
  'NATR',
  'NANX',
  'MX',
  'MVIS',
  'MVBF',
  'MTEX',
  'MTEM',
  'MRNS',
  'MRCC',
  'MPB',
  'MOSY',
  'MOJO',
  'MNOV',
  'MN',
  'MITK',
  'MHH',
  'MGEN',
  'MFNC',
  'MEIP',
  'MDVL',
  'MCEP',
  'MCBC',
  'MBOT',
  'MATN',
  'LYTS',
  'LWLG',
  'LUVU',
  'LTBR',
  'LSBK',
  'LPTH',
  'LPCN',
  'LODE',
  'LMB',
  'LEU',
  'LEDS',
  'LEAT',
  'LEAF',
  'LCNB',
  'LAWS',
  'KTCC',
  'KSPN',
  'KINS',
  'KIN',
  'JSDA',
  'JOUT',
  'JCTCF',
  'JCS',
  'ITP',
  'ITIC',
  'ITI',
  'ISR',
  'IROQ',
  'IRIX',
  'IPWR',
  'IPDN',
  'INTI',
  'INS',
  'INFU',
  'IMH',
  'IMBI',
  'IESC',
  'IDN',
  'ICCC',
  'IAIC',
  'HTGM',
  'HSTO',
  'HSON',
  'HRZN',
  'HPTO',
  'HMNF',
  'HMG',
  'HGBL',
  'HEPA',
  'HBP',
  'GV',
  'GROW',
  'GNSS',
  'GNCA',
  'GLGI',
  'GLAD',
  'GIGA',
  'GFN',
  'GFED',
  'GEC',
  'GCBC',
  'GALT',
  'GAIA',
  'FVE',
  'FSBW',
  'FRAF',
  'FNWB',
  'FNLC',
  'FMNB',
  'FMBM',
  'FMAO',
  'FLXT',
  'FFWM',
  'FCAP',
  'FBSS',
  'FBIO',
  'FALC',
  'EYPT',
  'EXEO',
  'EVOL',
  'EVFM',
  'ESXB',
  'ESSA',
  'ESP',
  'ESCA',
  'ERII',
  'EQUR',
  'ENG',
  'ENBP',
  'EMYB',
  'EMKR',
  'EMGCQ',
  'ELOX',
  'ELMD',
  'EKSO',
  'EHTH',
  'EGAN',
  'EFSI',
  'ECOM',
  'EBMT',
  'EARN',
  'DXYN',
  'DWSN',
  'DSNY',
  'DMRC',
  'DLYT',
  'DLHC',
  'DJCO',
  'DIT',
  'DGLY',
  'DFFN',
  'DENR',
  'DARE',
  'CZWI',
  'CYTR',
  'CYCC',
  'CYBE',
  'CXDO',
  'CWST',
  'CVV',
  'CTSO',
  'CTG',
  'CSBB',
  'CRWS',
  'CRVW',
  'CRMZ',
  'CRMD',
  'CRK',
  'CRGS',
  'CREX',
  'CRDF',
  'CRAI',
  'CPTP',
  'CPST',
  'CPSH',
  'CPRX',
  'CPIX',
  'CPAH',
  'COMS',
  'COHU',
  'COHN',
  'COFS',
  'CNFN',
  'CNET',
  'CNBKA',
  'CMXC',
  'CMT',
  'CLSN',
  'CLRO',
  'CLRB',
  'CLIR',
  'CLFD',
  'CLCT',
  'CLBS',
  'CKX',
  'CJJD',
  'CIVB',
  'CIO',
  'CIIT',
  'CIA',
  'CHMG',
  'CGIX',
  'CFBK',
  'CEI',
  'CDZI',
  'CDXC',
  'CDTX',
  'CDNA',
  'CDMO',
  'CCUR',
  'CCEL',
  'CCBG',
  'CBLI',
  'CBFV',
  'CBAY',
  'CASH',
  'CARV',
  'CAPR',
  'CALA',
  'BXC',
  'BWEN',
  'BTN',
  'BSTG',
  'BSRR',
  'BSQR',
  'BRG',
  'BPTH',
  'BKEP',
  'BIOL',
  'BIOC',
  'BICX',
  'BDGE',
  'BCOV',
  'BBI',
  'AWH',
  'AUTO',
  'ATRS',
  'ATNM',
  'ATLO',
  'ATLC',
  'ASUR',
  'ASTC',
  'ASPU',
  'ASPN',
  'ASMB',
  'ARTW',
  'ARDX',
  'APT',
  'APEX',
  'APDN',
  'AP',
  'ANFC',
  'ANDR',
  'AMTX',
  'AMSWA',
  'AMRK',
  'AMRB',
  'ALT',
  'ALSK',
  'ALDX',
  'AIM',
  'AHH',
  'AGRX',
  'AERI',
  'ADMT',
  'ADMP',
  'ADMA',
  'ACUR',
  'ACU',
  'ACRX',
  'ACHV',
  'ACFN',
  'ACER',
  'ABMC',
  'ABIO',
  'ABEO',
  'AAME'],
 '2020-03-31': ['WYY',
  'WATT',
  'VIVE',
  'UTI',
  'TOMZ',
  'TNXP',
  'TMQ',
  'TIKK',
  'TGHI',
  'TCON',
  'SOTK',
  'SNSS',
  'SHSP',
  'SAR',
  'SAMG',
  'RESN',
  'REI',
  'QTNT',
  'PURE',
  'PLX',
  'PFBX',
  'ORGS',
  'OPGN',
  'OPCH',
  'ONCS',
  'NLST',
  'MTEX',
  'LEDS',
  'LAWS',
  'ITI',
  'IRIX',
  'IPWR',
  'IDN',
  'GLYC',
  'GLGI',
  'FTLF',
  'EVOK',
  'ESSA',
  'EBMT',
  'CYCC',
  'CVCY',
  'CPAH',
  'CLIR',
  'CDXC',
  'CASH',
  'CAPR',
  'BIOC',
  'BBQ',
  'ASPU',
  'ARDX',
  'APT',
  'APDN',
  'AMRK',
  'ABIO'],
 '2019-12-31': ['ZIVO',
  'XSPA',
  'WYY',
  'WATT',
  'VNRX',
  'VIVE',
  'VASO',
  'UTI',
  'UFPT',
  'UBOH',
  'TSBK',
  'TNXP',
  'TKOI',
  'TIKK',
  'TCON',
  'TCFC',
  'TAYD',
  'SWKH',
  'STKS',
  'SOTK',
  'SNSS',
  'SNCA',
  'SMIT',
  'SGLB',
  'SFST',
  'SENEA',
  'SEEL',
  'SCON',
  'SAR',
  'SAL',
  'RM',
  'QTNT',
  'QCRH',
  'PULM',
  'PSTV',
  'PLX',
  'PDEX',
  'PCYO',
  'PAYS',
  'ORC',
  'OPGN',
  'ONTX',
  'ONCT',
  'OEG',
  'NSTG',
  'NMRD',
  'NLST',
  'NKSH',
  'NAVB',
  'MTEX',
  'MMAC',
  'MLR',
  'MCBC',
  'LSBK',
  'LODE',
  'KTYB',
  'JCS',
  'ISR',
  'IRT',
  'IRMD',
  'IRIX',
  'IPWR',
  'INS',
  'IDN',
  'HRZN',
  'GLXZ',
  'GFN',
  'GCBC',
  'FNWB',
  'FNLC',
  'FMNB',
  'FBIZ',
  'EVTN',
  'ENG',
  'ELMD',
  'EKSO',
  'EHTH',
  'EGAN',
  'EFSI',
  'ECOM',
  'DXYN',
  'DSNY',
  'CXDO',
  'CWBC',
  'CSBB',
  'CRWS',
  'CRK',
  'CPRX',
  'CPAH',
  'CLRB',
  'CLIR',
  'CGIX',
  'CFBK',
  'CCNE',
  'CCBG',
  'CBFV',
  'BSTG',
  'BSTC',
  'BSRR',
  'BPTH',
  'BIOL',
  'BIOC',
  'AUBN',
  'ATRS',
  'ATNM',
  'ASUR',
  'APDN',
  'AIM',
  'AGRX',
  'ADMP',
  'ADMA',
  'ACFN',
  'ABIO'],
 '2019-09-30': ['WVFC',
  'WATT',
  'VUZI',
  'VNRX',
  'VIVE',
  'VCYT',
  'UNAM',
  'UFPT',
  'UBFO',
  'TSBK',
  'TNXP',
  'TAT',
  'STRM',
  'SSNT',
  'SRNA',
  'SNSS',
  'SNMP',
  'SGLB',
  'SFST',
  'SEEL',
  'SCON',
  'SAL',
  'RM',
  'RILY',
  'RHE',
  'RCKY',
  'QCRH',
  'PURE',
  'PULM',
  'PSTV',
  'PPSI',
  'PLX',
  'PFBI',
  'PCYO',
  'PAYS',
  'ONCT',
  'ONCS',
  'OESX',
  'NLST',
  'NKSH',
  'MTEM',
  'MIND',
  'MGYR',
  'MCEP',
  'MCBC',
  'LODE',
  'LIQT',
  'LGL',
  'LEAT',
  'KTYB',
  'JCS',
  'ISTR',
  'ISR',
  'ISNS',
  'IRMD',
  'IRIX',
  'IPWR',
  'INTZ',
  'INS',
  'ICBK',
  'HRZN',
  'HBNC',
  'GLXZ',
  'GEOS',
  'GCBC',
  'FNLC',
  'FMNB',
  'FDBC',
  'FCAP',
  'EMGCQ',
  'EKSO',
  'ECOM',
  'EBMT',
  'CYTR',
  'CXDO',
  'CSBB',
  'CRVW',
  'CPRX',
  'CLRB',
  'CLIR',
  'CFBK',
  'CDTX',
  'CCNE',
  'CBLI',
  'CBFV',
  'BSTC',
  'BSRR',
  'BRG',
  'BPTH',
  'BLFS',
  'BIOC',
  'APDN',
  'AIRT',
  'AGRX',
  'ADMP',
  'ADMA',
  'ACRX',
  'ABIO'],
 '2019-06-30': ['WATT',
  'VIVE',
  'VCYT',
  'UFPT',
  'UBFO',
  'TSBK',
  'TRVN',
  'TPVG',
  'TNXP',
  'SRNA',
  'SFST',
  'SEEL',
  'SCON',
  'SAL',
  'QTNT',
  'PURE',
  'PULM',
  'PTN',
  'PFIN',
  'PAYS',
  'ONCS',
  'OESX',
  'NLST',
  'NCBS',
  'MVBF',
  'MLR',
  'MHH',
  'MCEP',
  'MCBC',
  'LIQT',
  'LGL',
  'KVHI',
  'JCS',
  'ISTR',
  'IRMD',
  'INTZ',
  'HSTO',
  'GLXZ',
  'GIGA',
  'FNLC',
  'FMAO',
  'FDBC',
  'FCAP',
  'FBIZ',
  'EKSO',
  'DGLY',
  'CXDO',
  'CSBB',
  'CPRX',
  'CNFN',
  'CLRB',
  'CFBK',
  'BSTC',
  'BSRR',
  'BPTH',
  'BOOM',
  'BIOC',
  'ATNM',
  'APDN',
  'AJX',
  'AGRX',
  'ACRX',
  'ACNB',
  'ABIO'],
 '2019-03-31': ['ZSAN',
  'WVFC',
  'WATT',
  'VPG',
  'VIVE',
  'VCYT',
  'UBFO',
  'TSBK',
  'TRVN',
  'TRNS',
  'TNXP',
  'THM',
  'SVBI',
  'SSY',
  'SNSS',
  'SNGX',
  'SESN',
  'SCON',
  'SAVA',
  'RCMT',
  'RC',
  'QTNT',
  'PULM',
  'PSTV',
  'PFBI',
  'PAYS',
  'ORGS',
  'OPTT',
  'ONCS',
  'OESX',
  'NSEC',
  'NMRD',
  'NLST',
  'NKSH',
  'NEON',
  'NCBS',
  'MGYR',
  'MCBC',
  'MATN',
  'LTRX',
  'LODE',
  'LIQT',
  'LGL',
  'JMP',
  'JCS',
  'ISTR',
  'IRMD',
  'IPWR',
  'INTZ',
  'INS',
  'ICD',
  'HUSA',
  'HALL',
  'GEOS',
  'GCBC',
  'FNLC',
  'FMNB',
  'FDBC',
  'FBIZ',
  'FBIO',
  'ENZ',
  'ENSV',
  'EGAN',
  'EBTC',
  'DIT',
  'CXDO',
  'CWCO',
  'CTEK',
  'CSBB',
  'CRVW',
  'CRDF',
  'CLRB',
  'CLIR',
  'CFBK',
  'BSRR',
  'BOOM',
  'BIOC',
  'BDR',
  'AUBN',
  'AGTC',
  'AGRX',
  'ACRX',
  'ACNB',
  'ABIO'],
 '2018-12-31': ['ZSAN',
  'ZAGG',
  'XONE',
  'WVFC',
  'WATT',
  'VIVE',
  'VCYT',
  'VCEL',
  'UPLD',
  'UONE',
  'ULBI',
  'UFPT',
  'UEC',
  'UBOH',
  'UBFO',
  'TSBK',
  'TRVN',
  'THM',
  'TESS',
  'TCI',
  'SVT',
  'SVBI',
  'SPRS',
  'SNSS',
  'SNCA',
  'SESN',
  'SCON',
  'SAVA',
  'SAL',
  'RVSB',
  'RM',
  'RAND',
  'QUIK',
  'QNST',
  'QMCI',
  'QCRH',
  'PSTV',
  'PFSW',
  'PFBI',
  'PBHC',
  'PAYS',
  'OXFD',
  'OPGN',
  'ONCT',
  'ONCS',
  'OGEN',
  'OFLX',
  'OCFC',
  'NTWK',
  'NOVC',
  'NLST',
  'NKSH',
  'NCBS',
  'NATH',
  'MMAC',
  'MLR',
  'MGYR',
  'MDVL',
  'MCBC',
  'MBCN',
  'MATN',
  'LODE',
  'LLEXQ',
  'LEAF',
  'JCAP',
  'IVAC',
  'IPWR',
  'INTZ',
  'INS',
  'HTGM',
  'HROW',
  'HOFT',
  'HBNC',
  'HBIO',
  'GSIT',
  'GNCA',
  'GCBC',
  'FZMD',
  'FTEK',
  'FSBW',
  'FNLC',
  'FMNB',
  'FIVN',
  'FDBC',
  'FCAP',
  'ENZN',
  'EML',
  'EKSO',
  'EGAN',
  'CTHR',
  'CSBB',
  'CRMD',
  'CRK',
  'CRDF',
  'CPHC',
  'CLSN',
  'CLRB',
  'CLIR',
  'CFBK',
  'CDTX',
  'CCBG',
  'CBKM',
  'BSTG',
  'BSTC',
  'BOTJ',
  'BOOM',
  'BLFS',
  'BKSC',
  'BFIN',
  'AWH',
  'AVEO',
  'AUBN',
  'ATRS',
  'ATNM',
  'ATLC',
  'ARL',
  'AMSC',
  'ALOT',
  'AIKI',
  'AGRX',
  'ABIO'],
 '2018-09-30': ['ZSAN',
  'ZAGG',
  'XXII',
  'WVFC',
  'WHF',
  'VPG',
  'UG',
  'UFPT',
  'UEC',
  'UBFO',
  'UBCP',
  'UAMY',
  'TRVN',
  'TRUP',
  'TCI',
  'SYNL',
  'SVT',
  'SLNG',
  'SIGA',
  'SAVA',
  'RYI',
  'RVSB',
  'RLH',
  'RCKY',
  'RCKT',
  'QUIK',
  'PSTV',
  'PFBI',
  'PCYO',
  'OPGN',
  'ONCS',
  'OFLX',
  'NWPX',
  'NTN',
  'NTIC',
  'NCBS',
  'MVIS',
  'MGYR',
  'MBCN',
  'MATN',
  'LOAN',
  'LMRK',
  'LEAT',
  'LAND',
  'ISTR',
  'IOR',
  'INSG',
  'INS',
  'INOD',
  'IIN',
  'IEC',
  'HWCC',
  'HCHC',
  'GNCA',
  'GEOS',
  'GCBC',
  'GALT',
  'GAIN',
  'FXNC',
  'FNLC',
  'FMNB',
  'FMAO',
  'FDBC',
  'FCAP',
  'FBIZ',
  'EGY',
  'EGAN',
  'CWCO',
  'CSBB',
  'CRVW',
  'CRK',
  'CRDF',
  'CLIR',
  'CBKM',
  'CBAT',
  'BSTG',
  'BSTC',
  'BLPH',
  'BLFS',
  'BBI',
  'ATRS',
  'ARL',
  'APYX',
  'APT',
  'AMSC',
  'ALIM',
  'AGRX',
  'ACNB',
  'ABIO'],
 '2018-06-30': ['ZSAN',
  'ZEUS',
  'WVFC',
  'WHF',
  'VTNR',
  'VPG',
  'VIVE',
  'UG',
  'UBFO',
  'UBCP',
  'TWIN',
  'TSBK',
  'SYNL',
  'STRT',
  'SNSS',
  'SNCA',
  'SMIT',
  'SFBC',
  'RVSB',
  'RSRV',
  'RCKT',
  'QNST',
  'PSTV',
  'PRSI',
  'PFIE',
  'PED',
  'PCYO',
  'PAYS',
  'OPHC',
  'OPGN',
  'OMEX',
  'NLTX',
  'NCBS',
  'MSB',
  'MPX',
  'MICT',
  'MHH',
  'MGYR',
  'MCCX',
  'MATN',
  'LTRX',
  'LMAT',
  'ISTR',
  'IPWR',
  'INTG',
  'IIN',
  'HWCC',
  'HTGM',
  'HROW',
  'HGBL',
  'HBNC',
  'GNCA',
  'GLG',
  'GCBC',
  'FRD',
  'FNLC',
  'FMNB',
  'FMAO',
  'FDBC',
  'ESCA',
  'ERII',
  'EFSI',
  'DSS',
  'CXDO',
  'CVLY',
  'CSBB',
  'CRDF',
  'COHU',
  'CLRB',
  'CLDB',
  'CIX',
  'CBIO',
  'BSTG',
  'BSTC',
  'BSRR',
  'BLFS',
  'BFIN',
  'ATNM',
  'ATHX',
  'ACNB',
  'ABIO'],
 '2018-03-31': ['XXII',
  'WVFC',
  'WHF',
  'VXRT',
  'VPG',
  'VABK',
  'UNB',
  'UCTT',
  'UBFO',
  'UBCP',
  'TSBK',
  'TRNS',
  'TIPT',
  'TGC',
  'SYNL',
  'SNSS',
  'SNFCA',
  'SNCA',
  'RCKY',
  'RCKT',
  'QNST',
  'QCRH',
  'PSTV',
  'PSTI',
  'PLXP',
  'PLBC',
  'PFIE',
  'PFBI',
  'PCYO',
  'OPGN',
  'ONCS',
  'NCBS',
  'MXC',
  'MTEM',
  'MRNS',
  'MPX',
  'MATN',
  'KTYB',
  'IPWR',
  'HWCC',
  'HTGM',
  'HSON',
  'HMG',
  'HGBL',
  'HBNC',
  'GCBC',
  'FXNC',
  'FRD',
  'FORD',
  'FNLC',
  'FMNB',
  'FMAO',
  'FFNW',
  'FDBC',
  'ENSV',
  'EFSI',
  'CXDO',
  'CSBB',
  'CRDF',
  'CPST',
  'CLSN',
  'CKX',
  'CIO',
  'CDMO',
  'CBIO',
  'CARV',
  'BSTG',
  'BSTC',
  'BLPH',
  'APDN',
  'ACNB',
  'ACER',
  'ABIO'],
 '2017-12-31': ['ZSAN',
  'WVVI',
  'WSTL',
  'WLFC',
  'VEC',
  'VCEL',
  'VALU',
  'USAP',
  'USAK',
  'UONE',
  'ULBI',
  'UCTT',
  'TNXP',
  'TACO',
  'SUWN',
  'STRM',
  'STCN',
  'SPRT',
  'SNSS',
  'SNFCA',
  'SNCA',
  'SMIT',
  'SLNG',
  'SCON',
  'SBFG',
  'RNWK',
  'RM',
  'RLGT',
  'RELL',
  'REEMF',
  'RCKY',
  'QUIK',
  'QTXB',
  'QNST',
  'PLXP',
  'PFSW',
  'PFIE',
  'PCYO',
  'PATI',
  'OTEL',
  'OPGN',
  'NVUS',
  'NVEE',
  'NUVR',
  'NERV',
  'NCBS',
  'MRNS',
  'MLR',
  'MCCX',
  'MATN',
  'LMST',
  'LMAT',
  'LEU',
  'LEE',
  'LCNB',
  'LAWS',
  'ITIC',
  'IPWR',
  'INTZ',
  'IMBI',
  'HWCC',
  'HTGM',
  'HSTO',
  'HPTO',
  'HNNA',
  'HEAR',
  'GVP',
  'GLYC',
  'GFN',
  'GCBC',
  'GALT',
  'FZMD',
  'FVE',
  'FRBK',
  'FNLC',
  'FMAO',
  'FLXT',
  'FDBC',
  'FALC',
  'EVOK',
  'ESP',
  'ESCA',
  'ERII',
  'EKSO',
  'DJCO',
  'DAIO',
  'CYTR',
  'CYCC',
  'CXDO',
  'CWGL',
  'CVV',
  'CUTR',
  'CTHR',
  'CSBR',
  'CRDF',
  'CPST',
  'CLSN',
  'CKX',
  'CIX',
  'CBAY',
  'CAPR',
  'BXC',
  'BSTG',
  'BCLI',
  'BBGI',
  'AVNW',
  'ATNM',
  'ASYS',
  'ASMB',
  'ARDX',
  'AOSL',
  'AKBA',
  'ACY',
  'ACHV',
  'ACER',
  'AAME'],
 '2017-09-30': ['ZSAN',
  'WVFC',
  'VOXX',
  'UBFO',
  'UBCP',
  'TWIN',
  'TRUP',
  'TCON',
  'TCFC',
  'SPRT',
  'SNCA',
  'SHYF',
  'SGA',
  'SFST',
  'RVSB',
  'QUIK',
  'QNST',
  'PTN',
  'PLXP',
  'PLPC',
  'PLBC',
  'PEYE',
  'OPGN',
  'OBLG',
  'NVUS',
  'NVEE',
  'NUVR',
  'NTN',
  'NCBS',
  'MSB',
  'MRNS',
  'MITK',
  'MGYR',
  'LUNA',
  'LOAN',
  'LMAT',
  'IPWR',
  'INTZ',
  'INTT',
  'INBK',
  'HTBK',
  'HSTO',
  'HPTO',
  'GROW',
  'GLYC',
  'GFED',
  'GCBC',
  'FNRN',
  'FLXT',
  'FIVN',
  'FDBC',
  'FALC',
  'EVBN',
  'EMYB',
  'DMRC',
  'DARE',
  'DAIO',
  'CXDO',
  'CUTR',
  'CTHR',
  'CSBR',
  'CNTY',
  'CNBKA',
  'CLSN',
  'CLDB',
  'CHMG',
  'CCBG',
  'CBAN',
  'CALA',
  'BWFG',
  'BSTG',
  'BFIN',
  'AXTI',
  'ASYS',
  'ASTC',
  'ARDX',
  'APT',
  'AOSL',
  'ACER'],
 '2017-06-30': ['ZSAN',
  'YEWB',
  'VABK',
  'UCTT',
  'UBFO',
  'TSBK',
  'TRUP',
  'TNXP',
  'TCFC',
  'TBK',
  'SNCA',
  'SMGI',
  'SCYX',
  'SCON',
  'RVSB',
  'REEMF',
  'QUIK',
  'PTN',
  'PRTS',
  'PLXP',
  'PLBC',
  'PFIE',
  'PAR',
  'NWIN',
  'NUVR',
  'NSPR',
  'MSB',
  'MRNS',
  'MPX',
  'MPB',
  'MCCX',
  'MCBC',
  'LPTH',
  'LMAT',
  'JCTCF',
  'IPWR',
  'HROW',
  'HPTO',
  'GLGI',
  'GCBC',
  'FSBW',
  'FNRN',
  'FMAO',
  'FLXT',
  'FDBC',
  'FCAP',
  'EVTN',
  'EVOK',
  'ECIA',
  'DARE',
  'DAIO',
  'CYCC',
  'CXDO',
  'CSBR',
  'CPST',
  'COHU',
  'CNBKA',
  'CMXC',
  'CLSN',
  'CLBS',
  'CDMO',
  'CCUR',
  'CBAN',
  'CALA',
  'BWFG',
  'BRG',
  'BLPH',
  'AWH',
  'AOSL',
  'ACER']}

In [51]:
a,b,c,d= trade ('WATT',announce_date('WATT','2020-03-31'), posn='long')
a,b,c,d

WATT

(2.07, 1.92, -0.07246376811594199, 'SLH')

In [52]:
# seems like     a,b,c,d= trade (cpy,announce_date(cpy,qtr)) and
#         a,b,c,d= trade (cpy,announce_date(cpy,qtr),posn='short') are the problem
#problem is with the trade function, not the announce date function

names = ['TCON','TMBR', 'TAT', 'BSTC','ZSAN','RCKT','TAT','LLEXQ','WSTL','NTRP','JCAP','RKDA','RMNI','PATI', 'ZEUS']

quarter = []
comp =[]
position =[]
bp=[]
sp=[]
pnl =[]
end=[]
i=0
j=0
for qtr in long_port:
    i=i+1
    #somehow i already referenced i before i assigned it in the function, the problem could be here or in the funciton
    for cpy in long_port[qtr]:
        quarter.append(qtr)
        comp.append(cpy)
        if cpy in names:
            break
        else:
            a,b,c,d= trade (cpy,announce_date(cpy,qtr), posn='long')
            bp.append(a)
            sp.append(b)
            pnl.append(c)
            end.append(d)
            position.append('long')
    print ('No. of quarters done:', i)
        
print ('long portfolio done')

for qtr in short_port:
    j=j+1
    for cpy in short_port[qtr]:
        quarter.append(qtr)
        comp.append(cpy)
        if cpy in names:
            break
        else:
            a,b,c,d= trade (cpy,announce_date(cpy,qtr),posn='short')
            bp.append(a)
            sp.append(b)
            pnl.append(c)
            end.append(d)
            position.append('short')
    print ('No. of quarters done:', j)

Final = pd.DataFrame(list(zip(quarter, comp, position, bp, sp, pnl, end)), columns =['Quarter', 'Ticker', 'Position', 'Pos. Open', 'Pos. Close', 'Profit', 'Pos. Status'])

No. of quarters done: 1
No. of quarters done: 2
WYY
WATT
VIVE
UTI
TOMZ
TNXP
TMQ
TIKK
TGHI
No. of quarters done: 3
ZIVO
XSPA
WYY
WATT
VNRX
VIVE
VASO
UTI
UFPT
UBOH
TSBK
TNXP
TKOI
TIKK
No. of quarters done: 4
WVFC
WATT
VUZI
VNRX
VIVE
VCYT
UNAM
UFPT
UBFO
TSBK
TNXP
No. of quarters done: 5
WATT
VIVE
VCYT
UFPT
UBFO
TSBK
TRVN
TPVG
TNXP
SRNA
SFST
SEEL
SCON
SAL
QTNT
PURE
PULM
PTN
PFIN
PAYS
ONCS
OESX
NLST
NCBS
MVBF
MLR
MHH
MCEP
MCBC
LIQT
LGL
KVHI
JCS
ISTR
IRMD
INTZ
HSTO
GLXZ
GIGA
FNLC
FMAO
FDBC
FCAP
FBIZ
EKSO
DGLY
CXDO
CSBB
CPRX
CNFN
CLRB
CFBK
No. of quarters done: 6
No. of quarters done: 7
No. of quarters done: 8
No. of quarters done: 9
No. of quarters done: 10
XXII
WVFC
WHF
VXRT
VPG
VABK
UNB
UCTT
UBFO
UBCP
TSBK
TRNS
TIPT
TGC
SYNL
SNSS
SNFCA
SNCA
RCKY
No. of quarters done: 11
No. of quarters done: 12
No. of quarters done: 13
No. of quarters done: 14
long portfolio done
No. of quarters done: 1
ZGNX
No. of quarters done: 2
No. of quarters done: 3
WHLM
UPLD
UAMY
TESS
TACO
SMGI
SHYF
PWFL
PRTS
PMD
PFIE
ORGS
OBLG
NERV
MRMD
MLP
MDLY
No. of quarters done: 4
ZGNX
No. of quarters done: 5
ZAGG
No. of quarters done: 6
ZAGG
No. of quarters done: 7
ZNOG
WLDN
WHLR
UTI
USNU
UNB
UMH
UCTT
TSRI
TGEN
SUNS
STRT
STRM
SRT
SOHO
SIMP
SCM
SCKT
RILY
RHE
REPH
REI
RC
RAIL
PTMN
PME
PMD
PFLT
PESI
PEIX
PCTI
PAR
ORN
OFS
OEG
OBCI
NWHM
No. of quarters done: 8
ZIVO
XENE
VOXX
VERU
UTI
USNU
TNLX
TMQ
TGEN
SWKH
SRT
SPRT
SKY
RHE
RELV
PAR
NWIN
MRMD
MRCC
MNOV
MLSS
MLP
MDLY
KIN
ITP
IMH
IMBI
GV
GROW
GNSS
GLAD
FVE
FLXS
FATE
EYPT
EQUR
ENZ
EMKR
DLYT
CVV
CRGS
CPTA
CPRX
CPAH
CMT
CLRO
CIVB
CDXC
CASI
BBW
ASYS
ASUR
ASPU
ALDX
AHPI
AEY
AERI
ACY
ABEO
No. of quarters done: 9
XONE
WSTG
VNRX
VERU
UTI
USIO
TGEN
TAYD
SUNS
SRT
SRNA
SMDM
SENEA
RELV
PTMN
PMD
PFLT
PEIX
OEG
NTIP
MVIS
MSN
MRMD
MN
MLP
MFIN
MEIP
MDLY
LCUT
LCNB
LAND
KTCC
KIN
JSDA
No. of quarters done: 10
ZIVO
XSPA
VNRX
VIDE
VERU
VASO
UWHR
USIO
UNAM
UMH
TSQ
TAYD
SUNS
SRT
SRNA
SPKE
SIMP
SGMA
SENEA
No. of quarters done: 11
ZIVO
ZGNX
YEWB
XTNT
XENE
XELB
WTT
WHLR
VGZ
VERU
VBTX
VASO
UWHR
UUU
USIO
UNAM
UBOH
TSQ
TMQ
TCFC
TAYD
SRT
SOHO
SNNY
SLCT
SGLB
SFST
SFDL
SAMG
SAL
RSSS
No. of quarters done: 12
ZGNX
VERU
UBOH
SMGI
RAIL
PROV
OXBR
LYTS
ICAD
GEOS
FENC
FBIO
ENG
CLRO
ACNB
ABCP
No. of quarters done: 13
ZNOG
ZGNX
XENE
WTT
WATT
VGZ
VERU
VASO
USIO
USAK
UBOH
TCI
SYNC
SVT
SMTX
SGLB
SANW
RAND
RAIL
PWOD
PROV
No. of quarters done: 14

In [53]:
Final.head(30)

       Quarter Ticker Position  Pos. Open  Pos. Close    Profit Pos. Status
0   2020-09-30   ZSAN     long      0.562       0.710  0.263345          PB
1   2020-06-30   ZSAN     long      2.070       1.920 -0.072464         SLH
2   2020-03-31    WYY     long      0.630       0.595 -0.055556         SLH
3   2020-03-31   WATT     long      7.240       6.570 -0.092541         SLH
4   2020-03-31   VIVE     long      0.800       0.920  0.150000          PB
5   2020-03-31    UTI     long      0.705       0.659 -0.065248         SLH
6   2020-03-31   TOMZ     long      1.720       1.620 -0.058140         SLH
7   2020-03-31   TNXP     long      3.400       3.750  0.102941          PB
8   2020-03-31    TMQ     long      0.050       0.040 -0.200000         SLH
9   2020-03-31   TIKK     long      0.110       0.090 -0.181818         SLH
10  2020-03-31   TGHI     long      0.510       0.590  0.156863          PB
11  2020-03-31   TCON     long      0.350       0.390  0.114286          PB
12  2019-12-31   ZIVO     long      1.040       0.900 -0.134615         SLH
13  2019-12-31   XSPA     long      4.980       4.570 -0.082329         SLH
14  2019-12-31    WYY     long      0.634       0.590 -0.069401         SLH
15  2019-12-31   WATT     long      0.020       0.040  1.000000          PB
16  2019-12-31   VNRX     long      8.700       7.760 -0.108046         SLH
17  2019-12-31   VIVE     long     39.900      35.550 -0.109023         SLH
18  2019-12-31   VASO     long     19.730      18.400 -0.067410         SLH
19  2019-12-31    UTI     long     27.600      25.400 -0.079710         SLH
20  2019-12-31   UFPT     long      0.990       0.740 -0.252525         SLH
21  2019-12-31   UBOH     long      0.060       0.050 -0.166667         SLH
22  2019-12-31   TSBK     long      4.100       3.800 -0.073171         SLH
23  2019-12-31   TNXP     long     15.980      16.480  0.031289         PSO
24  2019-12-31   TKOI     long      2.320       2.200 -0.051724         SLH
25  2019-12-31   TIKK     long      2.300       2.180 -0.052174         SLH
26  2019-12-31   TCON     long      5.190       4.280 -0.175337         SLH
27  2019-09-30   WVFC     long      4.480       3.960 -0.116071         SLH
28  2019-09-30   WATT     long     26.210      22.100 -0.156810         SLH
29  2019-09-30   VUZI     long      6.470       6.000 -0.072643         SLH

In [54]:
Final_by_quarter = Final.groupby('Quarter').sum()
Final_by_quarter

            Pos. Open  Pos. Close    Profit
Quarter
2017-06-30      1.020       1.089 -0.067647
2017-09-30    156.730     163.535 -0.370183
2017-12-31    371.205     365.030  0.592270
2018-03-31    394.545     392.111  0.236890
2018-06-30    290.307     286.512  0.378765
2018-09-30    413.673     385.539  3.314754
2018-12-31    320.560     308.913  1.401436
2019-03-31     61.760      65.220 -0.109618
2019-06-30    767.423     770.112  2.386768
2019-09-30    224.803     216.310 -0.684362
2019-12-31    377.262     363.443 -0.130670
2020-03-31     16.219      15.775  0.088116
2020-06-30     13.270      15.594 -0.382790
2020-09-30      7.762       7.070  0.380012

In [55]:
Final_by_quarter.reset_index(inplace=True)

# Calculating final NAV

In [56]:
Final_by_quarter

       Quarter  Pos. Open  Pos. Close    Profit
0   2017-06-30      1.020       1.089 -0.067647
1   2017-09-30    156.730     163.535 -0.370183
2   2017-12-31    371.205     365.030  0.592270
3   2018-03-31    394.545     392.111  0.236890
4   2018-06-30    290.307     286.512  0.378765
5   2018-09-30    413.673     385.539  3.314754
6   2018-12-31    320.560     308.913  1.401436
7   2019-03-31     61.760      65.220 -0.109618
8   2019-06-30    767.423     770.112  2.386768
9   2019-09-30    224.803     216.310 -0.684362
10  2019-12-31    377.262     363.443 -0.130670
11  2020-03-31     16.219      15.775  0.088116
12  2020-06-30     13.270      15.594 -0.382790
13  2020-09-30      7.762       7.070  0.380012

In [57]:
# lets say we start with a portfolio of 1,000,000 USD
d = { 'Quarter':(Final_by_quarter['Quarter']),'Profit in Percentage':(Final_by_quarter['Profit'])}

NAV = pd.DataFrame(data = d)
NAV['end NAV'] = None
NAV

       Quarter  Profit in Percentage end NAV
0   2017-06-30             -0.067647    None
1   2017-09-30             -0.370183    None
2   2017-12-31              0.592270    None
3   2018-03-31              0.236890    None
4   2018-06-30              0.378765    None
5   2018-09-30              3.314754    None
6   2018-12-31              1.401436    None
7   2019-03-31             -0.109618    None
8   2019-06-30              2.386768    None
9   2019-09-30             -0.684362    None
10  2019-12-31             -0.130670    None
11  2020-03-31              0.088116    None
12  2020-06-30             -0.382790    None
13  2020-09-30              0.380012    None

In [58]:
profit_percentage = list (NAV['Profit in Percentage'])

In [59]:
NAV_end = [1000000]
NAV_end[0]

1000000

In [60]:
for i in profit_percentage:
    print (i)
    j = 0
    print(j)
    period_NAV = NAV_end[j]*(1+i)
    NAV_end.append(period_NAV)
    
    j=j+1

-0.06764705882352937
0
-0.3701826538775279
0
0.5922697798378967
0
0.23689002092555791
0
0.3787645765473893
0
3.3147537291891926
0
1.4014355240033594
0
-0.10961800933626942
0
2.3867676569034453
0
-0.6843623275700549
0
-0.1306698548413428
0
0.088116245636986
0
-0.3827898550724637
0
0.3800118623962038
0

In [61]:
NAV_end

[1000000,
 932352.9411764706,
 629817.3461224721,
 1592269.7798378968,
 1236890.020925558,
 1378764.5765473892,
 4314753.729189192,
 2401435.524003359,
 890381.9906637305,
 3386767.6569034453,
 315637.6724299451,
 869330.1451586572,
 1088116.2456369859,
 617210.1449275363,
 1380011.862396204]

In [68]:
Final_by_quarter.to_csv('../dataset/Final_by_quarter.csv',index = False)
Final_by_quarter
#export the dataframe

       Quarter  Pos. Open  Pos. Close    Profit
0   2017-06-30      1.020       1.089 -0.067647
1   2017-09-30    156.730     163.535 -0.370183
2   2017-12-31    371.205     365.030  0.592270
3   2018-03-31    394.545     392.111  0.236890
4   2018-06-30    290.307     286.512  0.378765
5   2018-09-30    413.673     385.539  3.314754
6   2018-12-31    320.560     308.913  1.401436
7   2019-03-31     61.760      65.220 -0.109618
8   2019-06-30    767.423     770.112  2.386768
9   2019-09-30    224.803     216.310 -0.684362
10  2019-12-31    377.262     363.443 -0.130670
11  2020-03-31     16.219      15.775  0.088116
12  2020-06-30     13.270      15.594 -0.382790
13  2020-09-30      7.762       7.070  0.380012

In [63]:
# we form a final_NAV csv and then export it
df = pd.DataFrame(columns=['final NAV','quarter'])

In [64]:
temp = list(Final_by_quarter['Quarter'])
temp

['2017-06-30',
 '2017-09-30',
 '2017-12-31',
 '2018-03-31',
 '2018-06-30',
 '2018-09-30',
 '2018-12-31',
 '2019-03-31',
 '2019-06-30',
 '2019-09-30',
 '2019-12-31',
 '2020-03-31',
 '2020-06-30',
 '2020-09-30']

In [65]:
# we need to insert this quarter because we start taking position at this date
temp.insert(0,'2017-03-31')

In [66]:
df['final NAV'] = NAV_end
df['quarter'] = temp
df

       final NAV     quarter
0   1.000000e+06  2017-03-31
1   9.323529e+05  2017-06-30
2   6.298173e+05  2017-09-30
3   1.592270e+06  2017-12-31
4   1.236890e+06  2018-03-31
5   1.378765e+06  2018-06-30
6   4.314754e+06  2018-09-30
7   2.401436e+06  2018-12-31
8   8.903820e+05  2019-03-31
9   3.386768e+06  2019-06-30
10  3.156377e+05  2019-09-30
11  8.693301e+05  2019-12-31
12  1.088116e+06  2020-03-31
13  6.172101e+05  2020-06-30
14  1.380012e+06  2020-09-30

In [67]:
df.to_csv('../dataset/final_NAV.csv')